import { Engagement, EngagementAlert, ReviewItem, Company, TeamUser } from '@/types'

function noResponse(since: string): EngagementAlert {
  return { type: 'no_response', label: `No reply in 48h — since ${since}`, severity: 'high', since }
}
function followUp(since: string): EngagementAlert {
  return { type: 'follow_up_due', label: `Sent ${since} — time to follow up`, severity: 'medium', since }
}
function eventApproaching(label: string): EngagementAlert {
  return { type: 'event_approaching', label, severity: 'high' }
}
function invoiceOverdue(): EngagementAlert {
  return { type: 'invoice_overdue', label: 'Invoice unpaid — 32 days outstanding', severity: 'high' }
}

export const MOCK_ENGAGEMENTS: Engagement[] = [

  // ── PROSPECTS ──────────────────────────────────────────────────────────────

  // inquiry — fresh inbound this morning, no response yet
  {
    id: 'e1',
    created_at: '2026-03-30T08:45:00Z',
    updated_at: '2026-03-30T08:45:00Z',
    last_activity_at: '2026-03-30T08:45:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Accenture',
    source: 'Website inquiry',
    contacts: [{ id: 'c1a', first_name: 'Anika', last_name: 'Thomas', email: 'anika.thomas@accenture.com', title: 'VP Inclusion & Diversity', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Inclusive Negotiation Practices',
    event_format: 'virtual', audience_size: 250,
    notes: 'Inbound this morning via website contact form. Interested in Q3 virtual workshop for underrepresented talent.',
    comms: [{
      id: 'cm1a', type: 'email_inbound', date: '2026-03-30T08:45:00Z',
      subject: 'Speaking Inquiry — Inclusion & Negotiation Workshop',
      body: "Hello,\n\nI'm the VP of Inclusion & Diversity at Accenture and came across Dr. Taheripour's work through her Wharton profile. Her approach to negotiation resonated deeply with our current programming goals.\n\nWe're planning a virtual workshop in Q3 focused on helping underrepresented talent negotiate more effectively in corporate settings. Would she be available for a 60-90 minute session?\n\nWarm regards,\nAnika Thomas\nVP, Inclusion & Diversity\nAccenture",
      from_name: 'Anika Thomas', to_name: "Mori's Team", contact_id: 'c1a', channel: 'email', needs_response: true, response_due_by: '2026-04-01T14:00:00Z',
    }],
    alerts: [noResponse('Mar 30')],
  },

  // inquiry — came in Friday, still waiting on response
  {
    id: 'e9',
    created_at: '2026-03-27T14:30:00Z',
    updated_at: '2026-03-27T14:30:00Z',
    last_activity_at: '2026-03-27T14:30:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Nike',
    source: 'Direct inquiry',
    contacts: [{ id: 'c9a', first_name: 'Tanya', last_name: 'Rhodes', email: 'trhodes@nike.com', title: 'Director of Leadership Development', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Negotiation & Influence for Executives',
    event_format: 'in_person', audience_size: 200,
    event_date: '2026-06-09', event_city: 'Portland, OR',
    notes: 'Came in Friday afternoon. Senior leadership offsite, June in Portland. No response yet — needs reply today.',
    comms: [{
      id: 'cm9a', type: 'email_inbound', date: '2026-03-27T14:30:00Z',
      subject: 'Speaking Inquiry — Nike Executive Leadership Offsite',
      body: "Hi,\n\nMy name is Tanya Rhodes and I lead Leadership Development at Nike. We're planning an executive offsite in early June in Portland and Dr. Taheripour's work came highly recommended by a colleague at Wharton.\n\nWe're looking for a half-day keynote and workshop on negotiation and influence — ideally tailored for senior leaders. Could you share availability and rates?\n\nBest,\nTanya",
      from_name: 'Tanya Rhodes', to_name: "Mori's Team", contact_id: 'c9a', channel: 'email', needs_response: true, response_due_by: '2026-03-31T00:00:00Z',
    }],
    alerts: [noResponse('Mar 27')],
  },

  // outreach — team reached out, no reply yet
  {
    id: 'e10',
    created_at: '2026-03-26T11:00:00Z',
    updated_at: '2026-03-26T11:00:00Z',
    last_activity_at: '2026-03-26T11:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Salesforce',
    source: 'Outreach by team',
    contacts: [{ id: 'c10a', first_name: 'Marcus', last_name: 'Lin', email: 'mlin@salesforce.com', title: 'VP People & Culture', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'The Art of Negotiation for Sales Leaders',
    event_format: 'virtual', audience_size: 500,
    event_date: '2026-06-18', event_city: 'Virtual',
    notes: 'EA identified this as a strong fit — Salesforce runs a large virtual summit in June. No response yet.',
    comms: [{
      id: 'cm10a', type: 'email_outbound', date: '2026-03-26T11:00:00Z',
      subject: 'Speaker Introduction — Dr. Mori Taheripour',
      body: "Hi Marcus,\n\nWe're reaching out on behalf of Dr. Mori Taheripour, Wharton professor and author of Bring Yourself. We believe her work on negotiation would resonate strongly with your sales leadership community.\n\nShe's available for your June summit and would love to connect. I've attached her speaker profile for reference.\n\nWould you be open to a brief call?\n\nBest,\nSarah K.\nBooking, Dr. Mori Taheripour",
      from_name: "Mori's Team", to_name: 'Marcus Lin', contact_id: 'c10a', staff_name: 'Sarah K.', channel: 'email', needs_response: false,
    }],
    alerts: [followUp('Mar 26')],
  },

  // outreach — referral-based, high potential, first touch sent
  {
    id: 'e11',
    created_at: '2026-03-24T14:00:00Z',
    updated_at: '2026-03-24T14:00:00Z',
    last_activity_at: '2026-03-24T14:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Mayo Clinic',
    source: 'Referral from Goldman Sachs',
    contacts: [{ id: 'c11a', first_name: 'Sarah', last_name: 'Okonkwo', email: 'sokonkwo@mayo.edu', title: 'Chief Human Resources Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true }],
    topic: 'Negotiation & Difficult Conversations for Healthcare Leaders',
    event_format: 'in_person', audience_size: 150,
    event_city: 'Rochester, MN',
    notes: 'Warm referral from James Okafor at Goldman. Sarah is the CHRO — high-quality lead. First touch sent Monday.',
    comms: [{
      id: 'cm11a', type: 'email_outbound', date: '2026-03-24T14:00:00Z',
      subject: 'Introduction — Dr. Mori Taheripour (via James Okafor, Goldman Sachs)',
      body: "Hi Sarah,\n\nJames Okafor at Goldman Sachs suggested I reach out. He spoke highly of Dr. Mori Taheripour's session with their leadership team and felt her work would resonate deeply with Mayo Clinic's leadership programs.\n\nDr. Taheripour is a Wharton professor and author who specializes in negotiation and difficult conversations — with a particular focus on high-stakes, relationship-driven environments.\n\nWould you have 20 minutes for a brief call?\n\nBest,\nRyan G.",
      from_name: "Mori's Team", to_name: 'Sarah Okonkwo', contact_id: 'c11a', staff_name: 'Ryan G.', channel: 'email', needs_response: false,
    }],
    alerts: [followUp('Mar 24')],
  },

  // in_contact — bureau intro, had a call, awaiting follow-up
  {
    id: 'e2',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-27T10:00:00Z',
    last_activity_at: '2026-03-27T10:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Microsoft',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [
      { id: 'c2a', first_name: 'Lauren', last_name: 'Prescott', email: 'lprescott@microsoft.com', title: 'Director, Global Learning', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c2b', first_name: 'James', last_name: 'Hollis', email: 'jhollis@kepplerspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Microsoft LEAP Leadership Summit',
    event_date: '2026-09-10',
    event_location: 'Microsoft Campus', event_city: 'Redmond, WA',
    event_format: 'in_person', audience_size: 300,
    topic: 'The Negotiation Mindset', session_length: 60, fee: 26000,
    travel_covered: true, hotel_covered: true,
    notes: 'Good intro call Mar 20 with Lauren. She is enthusiastic but waiting on internal budget sign-off. Sent follow-up Mar 25.',
    comms: [
      { id: 'cm2a', type: 'email_inbound', date: '2026-03-20T09:00:00Z', subject: 'Microsoft LEAP Summit — Speaker Inquiry', body: 'Initial outreach via Keppler. Microsoft interested in a keynote for their LEAP program leadership summit in September.', from_name: 'James Hollis', to_name: "Mori's Team", contact_id: 'c2b', channel: 'email', needs_response: false },
      { id: 'cm2b', type: 'call', date: '2026-03-20T14:00:00Z', subject: 'Intro call with Lauren Prescott — 30 min', body: "Great call. Lauren is a big fan of Bring Yourself and already has a topic in mind. Budget approval is the only hurdle — she expects to hear back from her VP by end of month.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm2c', type: 'email_outbound', date: '2026-03-25T10:00:00Z', subject: "Re: Microsoft LEAP — Next Steps", body: "Hi Lauren,\n\nGreat connecting last week. I wanted to follow up and see if there's any update on budget approval. We're happy to hold the Sep 10 date while you finalize internally.\n\nLet me know if you need any additional materials.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Lauren Prescott', contact_id: 'c2a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
    ],
    alerts: [followUp('Mar 25')],
  },

  // in_contact — multi-contact, active thread, Mori involved directly
  {
    id: 'e12',
    created_at: '2026-03-18T09:00:00Z',
    updated_at: '2026-03-29T16:00:00Z',
    last_activity_at: '2026-03-29T16:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Amazon',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c12a', first_name: 'Patricia', last_name: 'Yuen', email: 'pyuen@amazon.com', title: 'Global Head of L&D', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c12b', first_name: 'Carlos', last_name: 'Mendes', email: 'cmendes@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    topic: 'Inclusive Leadership & Negotiation',
    event_format: 'hybrid', audience_size: 800,
    event_date: '2026-08-20', event_city: 'Seattle, WA',
    fee: 32000, travel_covered: true, hotel_covered: true,
    notes: 'Large hybrid event — 800 attendees in-person + virtual. Patricia is the real decision maker; Carlos is just the conduit. Sent speaker packet yesterday.',
    comms: [
      { id: 'cm12a', type: 'email_inbound', date: '2026-03-18T09:00:00Z', subject: 'Amazon Leadership Conference — Speaker Inquiry', body: 'Via Washington Speakers Bureau. Patricia Yuen at Amazon interested in Dr. Taheripour for their annual leadership conference in August.', from_name: 'Carlos Mendes', to_name: "Mori's Team", contact_id: 'c12b', channel: 'email', needs_response: false },
      { id: 'cm12b', type: 'call', date: '2026-03-24T15:00:00Z', subject: 'Intro call with Patricia Yuen — 45 min', body: "Excellent call. Patricia has read Bring Yourself and came with prepared questions. She wants a hybrid format with breakout components — something Mori hasn't done at this scale. Patricia said she'll push this through internally.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm12c', type: 'email_outbound', date: '2026-03-29T16:00:00Z', subject: 'Re: Amazon Leadership Conference — Speaker Packet + Hybrid Format Notes', body: "Hi Patricia,\n\nReally enjoyed our conversation last week. As discussed, I'm attaching Mori's full speaker packet along with some notes on how she's structured hybrid keynotes in the past — including the Q&A and breakout components.\n\nLet us know when you'd like to connect again.\n\nBest,\nRyan G.", from_name: "Mori's Team", to_name: 'Patricia Yuen', contact_id: 'c12a', staff_name: 'Ryan G.', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // discussing — fee negotiation actively happening
  {
    id: 'e3',
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-29T09:00:00Z',
    last_activity_at: '2026-03-29T09:00:00Z',
    section: 'prospects',
    prospect_step: 'discussing',
    engagement_flags: [], post_event_flags: [],
    organization: 'Vistage Worldwide',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c3a', first_name: 'David', last_name: 'Koslowski', email: 'dkoslowski@vistage.com', title: 'Program Director', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true },
      { id: 'c3b', first_name: 'Nina', last_name: 'Okafor', email: 'nokafor@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Vistage CEO Peer Group Summit',
    event_date: '2026-07-22',
    event_location: 'Marriott Marquis', event_city: 'Chicago, IL',
    event_format: 'in_person', audience_size: 120,
    topic: 'Navigating Difficult Conversations as a CEO',
    session_length: 90, fee: 25000,
    travel_covered: true, hotel_covered: true,
    notes: 'Three rounds of back-and-forth on fee. David keeps coming back at $22k for 90 min. Holding firm at $25k — Nina agrees this is the right move.',
    comms: [
      { id: 'cm3a', type: 'email_inbound', date: '2026-03-15T10:00:00Z', subject: 'Vistage CEO Summit — Speaker Inquiry', body: 'Via Washington Speakers Bureau. Interested in Dr. Taheripour for July CEO summit in Chicago.', from_name: 'Nina Okafor', to_name: "Mori's Team", contact_id: 'c3b', channel: 'email', needs_response: false },
      { id: 'cm3b', type: 'call', date: '2026-03-18T13:00:00Z', subject: 'Discovery call — 25 min', body: 'Good call with David. Very interested in the topic. Fee will be the sticking point — he already mentioned budget constraints.', from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm3c', type: 'email_outbound', date: '2026-03-20T09:00:00Z', subject: 'Re: Vistage Summit — Proposal', body: 'Sent formal proposal: 90 min keynote + Q&A at $25,000. Travel and hotel required.', from_name: "Mori's Team", to_name: 'David Koslowski', contact_id: 'c3a', staff_name: 'EA', channel: 'email', needs_response: false },
      { id: 'cm3d', type: 'email_inbound', date: '2026-03-25T11:00:00Z', subject: 'Re: Vistage Summit — Counter Proposal', body: "Hi, we appreciate the proposal. Our budget for this session tops out at $22,000 — is there any flexibility? Happy to discuss.", from_name: 'David Koslowski', to_name: "Mori's Team", contact_id: 'c3a', channel: 'email', needs_response: false },
      { id: 'cm3e', type: 'email_outbound', date: '2026-03-26T10:00:00Z', subject: 'Re: Vistage Summit — Response to Counter', body: "Hi David,\n\nThank you for coming back to us. We've reviewed your counter and unfortunately aren't able to move on the fee for a 90-minute engagement. Dr. Taheripour's rate for this format is $25,000.\n\nWe could offer a 60-minute keynote at $20,000 if that's more workable — the session would still be comprehensive but more tightly structured.\n\nLet us know how you'd like to proceed.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'David Koslowski', contact_id: 'c3a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm3f', type: 'email_inbound', date: '2026-03-29T09:00:00Z', subject: 'Re: Vistage Summit — Final Check', body: "We still prefer the 90-minute format. Let me bring this back to our board one more time and come back to you by end of week.", from_name: 'David Koslowski', to_name: "Mori's Team", contact_id: 'c3a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // discussing — ready to move to contract, needs agreement sent
  {
    id: 'e13',
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-03-29T14:00:00Z',
    last_activity_at: '2026-03-29T14:00:00Z',
    section: 'prospects',
    prospect_step: 'discussing',
    engagement_flags: [], post_event_flags: [],
    organization: 'PwC',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c13a', first_name: 'Diana', last_name: 'Nakamura', email: 'diana.nakamura@pwc.com', title: 'Chief Talent Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
    ],
    topic: 'Negotiation Strategy for Professional Services',
    event_format: 'in_person', audience_size: 300,
    event_date: '2026-06-25', event_city: 'New York, NY',
    fee: 24000, travel_covered: true, hotel_covered: false,
    notes: 'Diana confirmed 90-minute format yesterday. Ready to move to contract — needs agreement drafted and sent this week.',
    comms: [
      { id: 'cm13a', type: 'email_inbound', date: '2026-03-12T10:00:00Z', subject: 'PwC Partners Summit — Speaker Inquiry', body: 'Inquiry via Premier Speakers. Interested in June date for PwC annual partners summit in NYC.', from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: false },
      { id: 'cm13b', type: 'call', date: '2026-03-18T11:00:00Z', subject: 'Discovery call — 30 min', body: "Strong chemistry. Diana is a former Wharton student and already knows Mori's work. Very aligned on topic. Only question is format — 60 vs 90 min.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm13c', type: 'email_outbound', date: '2026-03-22T09:00:00Z', subject: 'Re: PwC Partners Summit — Format Options', body: "Sent Diana a breakdown of both format options with sample agendas for each.", from_name: "Mori's Team", to_name: 'Diana Nakamura', contact_id: 'c13a', staff_name: 'EA', channel: 'email', needs_response: false },
      { id: 'cm13d', type: 'email_inbound', date: '2026-03-29T14:00:00Z', subject: 'Re: PwC Partners Summit — Confirmed: 90-Minute Format', body: "Hi,\n\nAfter reviewing the sample agendas we'd like to move forward with the 90-minute deep-dive format. Can you send over a draft agreement and confirm the fee?\n\nLooking forward to working with Dr. Taheripour.\n\nDiana", from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: true },
    ],
    alerts: [noResponse('Mar 29')],
  },

  // proposal — contract drafted, sent, awaiting signature
  {
    id: 'e14',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-28T14:00:00Z',
    last_activity_at: '2026-03-28T14:00:00Z',
    section: 'prospects',
    prospect_step: 'proposal',
    engagement_flags: [], post_event_flags: [],
    organization: 'Citi',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [
      { id: 'c14a', first_name: 'Nadia', last_name: 'Hassan', email: 'nhassan@citi.com', title: 'Managing Director, Talent & OD', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c14b', first_name: 'Erin', last_name: 'Cho', email: 'echo@kepplerspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Citi Women in Finance Leadership Day',
    event_date: '2026-05-29',
    event_location: '388 Greenwich St', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 175,
    topic: 'Negotiating Your Career: Strategies for Women in Finance',
    session_length: 60, fee: 23000,
    travel_covered: false, hotel_covered: false,
    notes: 'Proposal sent Mar 25. Nadia indicated she needs signoff from her CFO — expected by end of this week.',
    comms: [
      { id: 'cm14a', type: 'email_inbound', date: '2026-03-05T09:00:00Z', subject: 'Citi Women in Finance — Speaker Inquiry', body: 'Via Keppler. Nadia Hassan at Citi interested in a keynote for their Women in Finance Leadership Day in late May.', from_name: 'Erin Cho', to_name: "Mori's Team", contact_id: 'c14b', channel: 'email', needs_response: false },
      { id: 'cm14b', type: 'call', date: '2026-03-12T11:00:00Z', subject: 'Intro call with Nadia — 30 min', body: "Good call. Nadia very engaged, has attended Mori's sessions before at Wharton executive ed. Fast mover — wants to finalize quickly.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm14c', type: 'email_outbound', date: '2026-03-25T09:00:00Z', subject: 'Citi Women in Finance — Formal Proposal', body: "Hi Nadia,\n\nThank you for the great conversation earlier this month. I'm pleased to send over a formal proposal for Dr. Taheripour's keynote at your Women in Finance Leadership Day on May 29.\n\nPlease find attached: speaker brief, session outline, and fee agreement. We look forward to your confirmation.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Nadia Hassan', contact_id: 'c14a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm14d', type: 'email_inbound', date: '2026-03-28T14:00:00Z', subject: 'Re: Citi Women in Finance — Proposal Received', body: "Hi Sarah,\n\nThank you — everything looks great. I'm waiting on a quick sign-off from our CFO which I expect by Friday. Will confirm then.\n\nNadia", from_name: 'Nadia Hassan', to_name: "Mori's Team", contact_id: 'c14a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // ── ENGAGEMENTS ────────────────────────────────────────────────────────────

  // contract_sent — legal holding it up
  {
    id: 'e4',
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-03-30T09:15:00Z',
    last_activity_at: '2026-03-30T09:15:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent'],
    post_event_flags: [],
    organization: 'Deloitte US',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c4a', first_name: 'Marcus', last_name: 'Webb', email: 'marcus.webb@deloitte.com', phone: '212-555-0202', title: 'Chief People Officer', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c4b', first_name: 'Jennifer', last_name: 'Park', email: 'jennifer.park@deloitte.com', title: 'EA to CPO', role: 'assistant', is_current_point_of_contact: false, notes: 'Handles all logistics for Marcus. CC on every email.' },
      { id: 'c4c', first_name: 'David', last_name: 'Chen', email: 'dchen@deloitte-legal.com', title: 'Associate General Counsel', role: 'legal', is_current_point_of_contact: false, notes: 'Reviewing contract — flagged IP and recording rights clauses' },
    ],
    event_name: 'Deloitte Leadership Forum 2026',
    event_date: '2026-06-04',
    event_location: 'Deloitte University', event_city: 'Westlake, TX',
    event_format: 'in_person', audience_size: 400,
    topic: 'The Art of Negotiation in High-Stakes Environments',
    session_length: 60, fee: 28000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Handheld mic preferred, full AV team on site, confidence monitor',
    notes: 'Contract sent Mar 20. Legal flagged two clauses — IP ownership and recording rights. Need to resolve this week; event is June 4.',
    comms: [
      { id: 'cm4a', type: 'email_outbound', date: '2026-03-20T10:00:00Z', subject: 'Deloitte Leadership Forum 2026 — Speaking Agreement', body: "Hi Marcus,\n\nPlease find attached the speaking agreement for the Deloitte Leadership Forum on June 4. I've cc'd Jennifer on logistics.\n\nLet us know if you have any questions.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Marcus Webb', contact_id: 'c4a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm4b', type: 'email_inbound', date: '2026-03-25T14:00:00Z', subject: 'Re: Deloitte Leadership Forum — Legal Review', body: "Hi,\n\nOur legal team (David Chen, cc'd) has reviewed the agreement. Two items to address: (1) the IP clause needs to specify that Deloitte retains no ownership of original content, and (2) we need a recording rights addendum. Nothing major — just standard Deloitte boilerplate.\n\nCould we do a quick call this week?\n\nMarcus", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'c4a', channel: 'email', needs_response: false },
      { id: 'cm4c', type: 'call', date: '2026-03-27T10:00:00Z', subject: 'Legal review call with David Chen — 20 min', body: "Good call. Both issues are minor. David drafting a short addendum. Should be back to us by Mar 30.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm4d', type: 'email_inbound', date: '2026-03-30T09:15:00Z', subject: 'Re: Deloitte Leadership Forum — Addendum Ready for Review', body: "Hi,\n\nDavid has drafted the addendum — attached. Please review and let us know if the language works on your end. Once agreed, Marcus will sign the full agreement.\n\nJennifer Park\nEA to Marcus Webb", from_name: 'Jennifer Park', to_name: "Mori's Team", contact_id: 'c4b', channel: 'email', needs_response: true, response_due_by: '2026-04-01T00:00:00Z' },
    ],
    alerts: [noResponse('Mar 30')],
  },

  // contract_signed — confirmed but advance sheet overdue
  {
    id: 'e5',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-03-20T14:00:00Z',
    last_activity_at: '2026-03-20T14:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed'],
    post_event_flags: [],
    organization: 'Wharton Executive Education',
    source: 'Repeat client',
    contacts: [{
      id: 'c5a', first_name: 'Rachel', last_name: 'Simmons',
      email: 'rsimmons@wharton.upenn.edu', phone: '215-555-0101',
      title: 'Director of Executive Education', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
      notes: 'Third engagement with Mori. Very organized, always early to respond. Prefers email.',
    }],
    event_name: 'Women in Leadership Summit 2026',
    event_date: '2026-05-14',
    event_location: 'Huntsman Hall, Room 300', event_city: 'Philadelphia, PA',
    event_format: 'in_person', audience_size: 250,
    topic: 'Negotiation & Influence for Executive Women',
    session_length: 75, fee: 22000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Lapel mic, clicker, HDMI, confidence monitor, recording setup',
    notes: 'Contract signed March 20. Advance sheet not yet drafted — event is May 14, 6 weeks out. Need to prioritize.',
    comms: [
      { id: 'cm5a', type: 'email_outbound', date: '2026-03-01T10:00:00Z', subject: 'Women in Leadership Summit — Speaking Agreement', body: "Hi Rachel,\n\nSo glad to be working together again. Please find attached the speaking agreement for May 14.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Rachel Simmons', contact_id: 'c5a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm5b', type: 'email_inbound', date: '2026-03-04T09:00:00Z', subject: 'Re: Women in Leadership Summit — Contract Signed', body: "Hi Sarah,\n\nSigned and returned — excited to have Mori back. Let me know what you need for the advance sheet when you're ready.\n\nRachel", from_name: 'Rachel Simmons', to_name: "Mori's Team", contact_id: 'c5a', channel: 'email', needs_response: false },
      { id: 'cm5c', type: 'stage_change', date: '2026-03-04T10:00:00Z', subject: 'Contract signed — moved to Confirmed', staff_name: 'Sarah K.', needs_response: false },
      { id: 'cm5d', type: 'email_inbound', date: '2026-03-20T14:00:00Z', subject: 'Women in Leadership Summit — Advance Sheet?', body: "Hi,\n\nJust checking in — we're now 8 weeks out from the event and I want to make sure we have the advance sheet finalized before our AV team locks in the room setup. Any timeline on when to expect it?\n\nThanks,\nRachel", from_name: 'Rachel Simmons', to_name: "Mori's Team", contact_id: 'c5a', channel: 'email', needs_response: true },
    ],
    alerts: [eventApproaching('Event May 14 — advance sheet overdue, Rachel is waiting')],
  },

  // advance_sheet_sent — fully locked, event is soon
  {
    id: 'e6',
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-03-28T11:00:00Z',
    last_activity_at: '2026-03-28T11:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed'],
    post_event_flags: [],
    organization: 'JPMorgan Chase',
    source: 'Direct outreach',
    contacts: [
      { id: 'c6a', first_name: 'Priya', last_name: 'Nair', email: 'priya.nair@jpmorgan.com', title: 'Managing Director, Talent', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c6b', first_name: 'Tom', last_name: 'Everett', email: 'tom.everett@jpmorgan.com', title: 'AV & Events Coordinator', role: 'av', is_current_point_of_contact: false, notes: 'Room confirmed — main auditorium, floor 2. AV check at 8:30am day of.' },
    ],
    event_name: "Chase Women's Network Annual Conference",
    event_date: '2026-04-22',
    event_location: '383 Madison Ave', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 180,
    topic: 'Negotiating Your Worth: Strategies for Senior Women',
    session_length: 45, fee: 18000,
    travel_covered: false, hotel_covered: false,
    av_needs: 'Podium mic, projector, no clicker needed — slides advanced by AV tech',
    notes: 'Everything locked. Event is April 22 — 23 days out. Tom confirmed AV setup. Priya sent final headcount last week.',
    comms: [
      { id: 'cm6a', type: 'email_outbound', date: '2026-03-10T09:00:00Z', subject: "Chase Women's Network — Advance Sheet", body: "Hi Priya,\n\nAttached is the advance sheet for the April 22 conference. Please review and confirm all details are accurate.\n\nAlso cc'ing Tom on AV logistics.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Priya Nair', contact_id: 'c6a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm6b', type: 'email_inbound', date: '2026-03-14T10:00:00Z', subject: "Re: Chase Women's Network — Advance Sheet Confirmed", body: "Hi Sarah,\n\nAll confirmed. One update: we've moved to the main auditorium on floor 2 — Tom will have everything set up. AV check is at 8:30am.\n\nCurrent headcount is 178. We're so excited to have Dr. Taheripour.\n\nPriya", from_name: 'Priya Nair', to_name: "Mori's Team", contact_id: 'c6a', channel: 'email', needs_response: false },
      { id: 'cm6c', type: 'email_inbound', date: '2026-03-28T11:00:00Z', subject: "Chase Conference — Final Headcount & Run of Show", body: "Hi,\n\nFinal headcount confirmed at 182. Attached is the full run of show — Dr. Taheripour is on at 10:15am following opening remarks. Please review and let us know if any adjustments needed.\n\nPriya", from_name: 'Priya Nair', to_name: "Mori's Team", contact_id: 'c6a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // day_of_ready — happening this week
  {
    id: 'e15',
    created_at: '2025-12-15T09:00:00Z',
    updated_at: '2026-03-29T10:00:00Z',
    last_activity_at: '2026-03-29T10:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: [],
    organization: 'Stanford Graduate School of Business',
    source: 'Direct — faculty referral',
    contacts: [
      { id: 'c15a', first_name: 'Elena', last_name: 'Vasquez', email: 'evasquez@gsb.stanford.edu', title: 'Director of Executive Programs', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true },
      { id: 'c15b', first_name: 'Chris', last_name: 'Tanaka', email: 'ctanaka@gsb.stanford.edu', title: 'Events Coordinator', role: 'assistant', is_current_point_of_contact: false, notes: 'Managing all day-of logistics. Pickup from hotel at 8am.' },
    ],
    event_name: 'GSB Executive Leadership Program — Negotiation Module',
    event_date: '2026-04-01',
    event_location: 'Knight Management Center', event_city: 'Stanford, CA',
    event_format: 'in_person', audience_size: 60,
    topic: 'Bring Yourself: Authentic Negotiation for Executive Leaders',
    session_length: 120, fee: 30000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Lapel mic, HDMI, whiteboard, no slides — Mori will facilitate discussion format',
    notes: 'Event is this Tuesday April 1. Everything confirmed. Chris picking Mori up at 8am from the Rosewood. Small executive cohort — intimate discussion format.',
    comms: [
      { id: 'cm15a', type: 'stage_change', date: '2026-01-10T11:00:00Z', subject: 'Contract signed', staff_name: 'Sarah K.', needs_response: false },
      { id: 'cm15b', type: 'email_outbound', date: '2026-03-15T09:00:00Z', subject: 'GSB Executive Program — Advance Sheet', body: "Hi Elena,\n\nAttached is the advance sheet for April 1. Please review and confirm everything is accurate.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Elena Vasquez', contact_id: 'c15a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm15c', type: 'email_inbound', date: '2026-03-18T10:00:00Z', subject: 'Re: GSB — Advance Sheet Confirmed', body: "Everything looks perfect. Chris will handle day-of. The cohort is very excited — several participants have read Bring Yourself already.\n\nElena", from_name: 'Elena Vasquez', to_name: "Mori's Team", contact_id: 'c15a', channel: 'email', needs_response: false },
      { id: 'cm15d', type: 'email_inbound', date: '2026-03-29T10:00:00Z', subject: 'GSB Tuesday — Final Details', body: "Hi,\n\nJust confirming all final details for Tuesday. Chris will meet Dr. Taheripour at the Rosewood Palo Alto at 8:00am. Session begins at 9:00am sharp.\n\nLooking forward to a wonderful morning.\n\nElena", from_name: 'Elena Vasquez', to_name: "Mori's Team", contact_id: 'c15a', channel: 'email', needs_response: false },
    ],
    alerts: [eventApproaching('Event April 1 — Tuesday, 2 days out')],
  },

  // ── POST-EVENT ─────────────────────────────────────────────────────────────

  // invoice sent, overdue — client says it's processing
  {
    id: 'e7',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-03-26T16:00:00Z',
    last_activity_at: '2026-03-26T16:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: ['invoice_sent'],
    organization: 'TechCorp',
    source: 'LinkedIn referral',
    contacts: [{
      id: 'c7a', first_name: 'Stephanie', last_name: 'Cho',
      email: 'scho@techcorp.io', title: 'Head of Learning & Development',
      role: 'primary', is_current_point_of_contact: true, status: 'client',
    }],
    event_name: 'TechCorp All-Hands Leadership Day',
    event_date: '2026-03-05',
    event_location: 'TechCorp HQ', event_city: 'San Francisco, CA',
    event_format: 'hybrid', audience_size: 600,
    topic: 'Negotiation Skills for Tech Leaders',
    session_length: 60, fee: 20000,
    travel_covered: true, hotel_covered: true,
    notes: 'Event went well — strong feedback. Invoice #2026-004 sent Mar 6 for $20,000. Due Mar 27. Now 3 days overdue.',
    comms: [
      { id: 'cm7a', type: 'email_outbound', date: '2026-03-06T09:00:00Z', subject: 'Invoice #2026-004 — TechCorp Leadership Day', body: "Hi Stephanie,\n\nThank you for a wonderful event yesterday. Please find attached Invoice #2026-004 for $20,000, due March 27.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Stephanie Cho', contact_id: 'c7a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm7b', type: 'email_inbound', date: '2026-03-08T11:00:00Z', subject: 'Re: Invoice — Thank you!', body: "Hi Sarah,\n\nReceived! The session was absolutely phenomenal — the feedback from the team has been overwhelming. Finance will process this on the 27th.\n\nSteph", from_name: 'Stephanie Cho', to_name: "Mori's Team", contact_id: 'c7a', channel: 'email', needs_response: false },
      { id: 'cm7c', type: 'email_inbound', date: '2026-03-26T16:00:00Z', subject: 'Re: Invoice #2026-004 — Payment Update', body: "Hi,\n\nSorry for the slight delay — finance had a system migration last week that held up a batch of payments. It's been released and should hit your account by Apr 4.\n\nSteph", from_name: 'Stephanie Cho', to_name: "Mori's Team", contact_id: 'c7a', channel: 'email', needs_response: false },
    ],
    alerts: [invoiceOverdue()],
  },

  // invoice paid, media received, pending final close-out
  {
    id: 'e16',
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-03-15T14:00:00Z',
    last_activity_at: '2026-03-15T14:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: ['invoice_sent', 'invoice_paid', 'media_uploaded'],
    organization: 'BlackRock',
    source: 'Referral from JPMorgan Chase',
    contacts: [{
      id: 'c16a', first_name: 'Sandra', last_name: 'Obi',
      email: 'sobi@blackrock.com', title: 'Head of Talent Development',
      role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
    }],
    event_name: "BlackRock Women's Leadership Forum",
    event_date: '2026-03-12',
    event_location: '50 Hudson Yards', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 220,
    topic: "Negotiation & Influence: A Framework for Senior Women",
    session_length: 60, fee: 25000,
    travel_covered: false, hotel_covered: false,
    notes: 'Excellent event March 12. Invoice paid March 15. Media received and uploaded. Needs marked complete.',
    comms: [
      { id: 'cm16a', type: 'email_outbound', date: '2026-03-13T09:00:00Z', subject: 'Invoice #2026-003 — BlackRock Women\'s Leadership Forum', body: "Hi Sandra,\n\nThank you for a wonderful event yesterday. Please find attached Invoice #2026-003 for $25,000, due April 3.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Sandra Obi', contact_id: 'c16a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm16b', type: 'email_inbound', date: '2026-03-15T14:00:00Z', subject: 'Re: Invoice + Media Files', body: "Hi Sarah,\n\nPayment sent this morning — you should see it within 1-2 business days. Also attaching the professional photos and video recording from the session as promised.\n\nThe feedback has been extraordinary — we'll definitely be back in touch for next year.\n\nSandra", from_name: 'Sandra Obi', to_name: "Mori's Team", contact_id: 'c16a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // fully complete — the gold standard reference engagement
  {
    id: 'e8',
    created_at: '2025-11-01T10:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
    last_activity_at: '2026-02-20T10:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: ['invoice_sent', 'invoice_paid', 'media_uploaded', 'marked_complete'],
    organization: 'Goldman Sachs',
    source: 'Repeat client',
    contacts: [{
      id: 'c8a', first_name: 'James', last_name: 'Okafor',
      email: 'jokafor@goldmansachs.com', title: 'Chief Learning Officer',
      role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
      notes: 'Third engagement with Goldman. James is a champion — always fast to pay, always sends media.',
    }],
    event_name: 'GS Leadership Accelerator — Winter Cohort',
    event_date: '2026-02-12', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 85, fee: 30000,
    session_length: 90,
    topic: 'Power, Persuasion, and the Negotiation Table',
    notes: 'Third time working with James and Goldman. Flawless — paid same week, sent HD video and professional photos. Already discussing fall cohort.',
    comms: [
      { id: 'cm8a', type: 'email_inbound', date: '2026-02-14T10:00:00Z', subject: 'Re: Invoice — Wire Sent + Media', body: "Sarah,\n\nWire sent this morning for the full amount. Attaching the session recording and photos from our media team — quality is excellent.\n\nThe cohort absolutely loved it. I've already spoken with my partner about bringing Mori back in October. Let's connect in April to discuss.\n\nJames", from_name: 'James Okafor', to_name: "Mori's Team", contact_id: 'c8a', channel: 'email', needs_response: false },
      { id: 'cm8b', type: 'stage_change', date: '2026-02-20T10:00:00Z', subject: 'Marked complete — payment confirmed, media uploaded', staff_name: 'Sarah K.', needs_response: false },
    ],
    alerts: [],
  },
  // ── MEDIA APPEARANCES ─────────────────────────────────────────────────────

  // podcast prospect — inbound inquiry, discussing topic angle
  {
    id: 'em1',
    created_at: '2026-03-27T10:00:00Z',
    updated_at: '2026-03-29T13:00:00Z',
    last_activity_at: '2026-03-29T13:00:00Z',
    section: 'prospects',
    event_type: 'podcast',
    prospect_step: 'discussing',
    engagement_flags: [], media_flags: [], post_event_flags: [],
    organization: 'How I Built This — Guy Raz / NPR',
    source: 'Direct outreach from producer',
    contacts: [{ id: 'cm1a_c', first_name: 'Jessica', last_name: 'Park', email: 'jpark@npr.org', title: 'Senior Producer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Negotiation, Authenticity & the Making of Bring Yourself',
    event_format: 'virtual',
    notes: 'NPR producer reached out directly. They want Mori for a full episode on how her negotiation philosophy informed writing the book. Back and forth on angle — they want more personal backstory, we want to keep it leadership-focused.',
    comms: [
      { id: 'cm_em1a', type: 'email_inbound', date: '2026-03-27T10:00:00Z', subject: 'How I Built This — Guest Invitation for Dr. Taheripour', body: "Hi,\n\nI'm a senior producer at How I Built This with Guy Raz. We've been following Dr. Taheripour's work and would love to have her on for a conversation about her journey — from professor to author to in-demand speaker — and how her negotiation philosophy shapes the way she operates.\n\nWould she be open to a 60-minute recorded conversation?\n\nJessica Park\nSenior Producer, How I Built This / NPR", from_name: 'Jessica Park', to_name: "Mori's Team", contact_id: 'cm1a_c', channel: 'email', needs_response: false },
      { id: 'cm_em1b', type: 'email_outbound', date: '2026-03-28T09:00:00Z', subject: 'Re: How I Built This — Thank You, Topic Discussion', body: "Hi Jessica,\n\nThank you for reaching out — Mori would be delighted to join. We'd love to focus the conversation around her leadership philosophy and the themes in Bring Yourself, particularly around authentic negotiation in high-stakes environments.\n\nCould we schedule a brief pre-call to align on the angle?\n\nBest,\nRyan G.", from_name: "Mori's Team", to_name: 'Jessica Park', contact_id: 'cm1a_c', staff_name: 'Ryan G.', channel: 'email', needs_response: false },
      { id: 'cm_em1c', type: 'email_inbound', date: '2026-03-29T13:00:00Z', subject: 'Re: How I Built This — Pre-Call Set for Apr 2', body: "Perfect — I've sent a calendar invite for a 20-minute pre-call on Wednesday April 2 at 2pm ET. We'll align on framing then. We're also open to the leadership angle — just want to make sure we get some of the personal journey woven in.\n\nJessica", from_name: 'Jessica Park', to_name: "Mori's Team", contact_id: 'cm1a_c', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // panel — confirmed, happening next month, bio/prep sent
  {
    id: 'em2',
    created_at: '2026-02-20T09:00:00Z',
    updated_at: '2026-03-22T11:00:00Z',
    last_activity_at: '2026-03-22T11:00:00Z',
    section: 'engagements',
    event_type: 'panel',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent', 'prep_sent'],
    post_event_flags: [],
    organization: 'World Economic Forum — Davos Connections Series',
    source: 'WEF invitation',
    contacts: [{ id: 'cm2a_c', first_name: 'Lena', last_name: 'Brandt', email: 'lbrandt@weforum.org', title: 'Program Director, Leadership', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'WEF Davos Connections — Women Redefining Negotiation',
    event_date: '2026-05-06',
    event_format: 'virtual',
    audience_size: 3500,
    topic: 'Women Redefining Negotiation in the 21st Century',
    fee: 8000,
    notes: 'Virtual panel — 4 panelists, 60 minutes, moderated. Mori is the anchor voice. Bio and prep questions sent. Lena confirmed all materials received.',
    comms: [
      { id: 'cm_em2a', type: 'email_inbound', date: '2026-02-20T09:00:00Z', subject: 'WEF Davos Connections Series — Panel Invitation', body: "Dear Dr. Taheripour,\n\nThe World Economic Forum would like to invite you to participate as a panelist in our Davos Connections virtual series on May 6. The topic: Women Redefining Negotiation in the 21st Century.\n\nThis is a 60-minute moderated panel with three other distinguished voices. Expected viewership: 3,500+.\n\nWould you be available?\n\nLena Brandt\nProgram Director, WEF", from_name: 'Lena Brandt', to_name: "Mori's Team", contact_id: 'cm2a_c', channel: 'email', needs_response: false },
      { id: 'cm_em2b', type: 'email_outbound', date: '2026-03-01T10:00:00Z', subject: 'Re: WEF Panel — Confirmed + Bio & Headshot', body: "Hi Lena,\n\nDr. Taheripour is delighted to participate. Attached is her official bio and high-resolution headshot for your promotional materials.\n\nPlease send over the prep questions when ready.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Lena Brandt', contact_id: 'cm2a_c', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm_em2c', type: 'email_inbound', date: '2026-03-22T11:00:00Z', subject: 'WEF Panel — Prep Questions + Zoom Details', body: "Hi Sarah,\n\nAll confirmed — bio received and approved. Attached are the moderator's prep questions for Dr. Taheripour's review. Zoom link and tech check details to follow next week.\n\nLena", from_name: 'Lena Brandt', to_name: "Mori's Team", contact_id: 'cm2a_c', channel: 'email', needs_response: false },
    ],
    alerts: [{ type: 'event_approaching', label: 'Panel May 6 — tech check not yet scheduled', severity: 'medium' }],
  },

  // interview — print, completed and published
  {
    id: 'em3',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-03-18T14:00:00Z',
    last_activity_at: '2026-03-18T14:00:00Z',
    section: 'post-event',
    event_type: 'interview',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent', 'prep_sent', 'day_of_ready'],
    post_event_flags: ['media_uploaded', 'marked_complete'],
    organization: 'Forbes',
    source: 'Editorial outreach',
    contacts: [{ id: 'cm3a_c', first_name: 'Rachel', last_name: 'Monroe', email: 'rmonroe@forbes.com', title: 'Senior Editor, Leadership', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'Forbes — "The Negotiators" Feature Series',
    event_date: '2026-03-10',
    event_format: 'virtual',
    topic: 'Why the Best Negotiators Never Bluff',
    notes: 'Published March 18. Strong pickup — 42k reads in first week. Rachel already asking about a follow-up piece.',
    comms: [
      { id: 'cm_em3a', type: 'email_inbound', date: '2026-02-01T10:00:00Z', subject: 'Forbes Leadership — Interview Request for "The Negotiators" Series', body: "Hi,\n\nI'm a senior editor at Forbes working on a feature series called 'The Negotiators' — profiles of the leading voices reshaping how we think about negotiation. Dr. Taheripour is at the top of our list.\n\nWe'd love a 45-minute conversation for a 1,500-word profile. No fee but strong readership exposure (avg 60k+ per piece).\n\nRachel Monroe\nForbes", from_name: 'Rachel Monroe', to_name: "Mori's Team", contact_id: 'cm3a_c', channel: 'email', needs_response: false },
      { id: 'cm_em3b', type: 'email_outbound', date: '2026-02-05T09:00:00Z', subject: 'Re: Forbes — Confirmed for Mar 10', body: "Hi Rachel,\n\nDr. Taheripour would be happy to participate. Confirmed for March 10 at 11am ET. Attaching bio and headshot.\n\nBest,\nRyan G.", from_name: "Mori's Team", to_name: 'Rachel Monroe', contact_id: 'cm3a_c', staff_name: 'Ryan G.', channel: 'email', needs_response: false },
      { id: 'cm_em3c', type: 'email_inbound', date: '2026-03-18T14:00:00Z', subject: 'Forbes Feature — Published Today!', body: "Hi,\n\nThe piece is live! Link attached — it's already getting strong traction. Dr. Taheripour's quotes are some of the best in the series.\n\nWould she be open to a follow-up piece later this year? We'd love to go deeper on the Wharton methodology.\n\nRachel", from_name: 'Rachel Monroe', to_name: "Mori's Team", contact_id: 'cm3a_c', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // livestream — upcoming, fully confirmed
  {
    id: 'em4',
    created_at: '2026-03-10T09:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
    last_activity_at: '2026-03-28T10:00:00Z',
    section: 'engagements',
    event_type: 'livestream',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent'],
    post_event_flags: [],
    organization: 'LinkedIn Live',
    source: 'LinkedIn editorial team',
    contacts: [{ id: 'cm4a_c', first_name: 'Marcus', last_name: 'Webb', email: 'mwebb@linkedin.com', title: 'Creator Partnerships Lead', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'LinkedIn Live — Negotiation Masterclass',
    event_date: '2026-04-15',
    event_format: 'virtual',
    audience_size: 10000,
    topic: 'Live Q&A: How to Negotiate Anything Without Losing Yourself',
    notes: 'LinkedIn reached out to feature Mori for a live creator event. Free — no fee but massive reach. Bio sent. Prep questions still needed.',
    comms: [
      { id: 'cm_em4a', type: 'email_inbound', date: '2026-03-10T09:00:00Z', subject: 'LinkedIn Live — Creator Feature Invitation', body: "Hi,\n\nWe're the LinkedIn Live editorial team and we'd love to feature Dr. Taheripour for a live negotiation masterclass on April 15. Expected audience: 8,000–12,000 live viewers plus replay.\n\nThis is a complimentary feature — no fee, but significant exposure to the LinkedIn professional community.\n\nMarcus Webb\nCreator Partnerships, LinkedIn", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'cm4a_c', channel: 'email', needs_response: false },
      { id: 'cm_em4b', type: 'email_outbound', date: '2026-03-15T10:00:00Z', subject: 'Re: LinkedIn Live — Confirmed for April 15', body: "Hi Marcus,\n\nDr. Taheripour would love to participate — April 15 works perfectly. Attaching bio and headshot for promotional use.\n\nCould you send over the format details and any prep questions you'd like her to review in advance?\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Marcus Webb', contact_id: 'cm4a_c', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm_em4c', type: 'email_inbound', date: '2026-03-28T10:00:00Z', subject: 'LinkedIn Live — Promo Assets Going Live + Format Details', body: "Hi Sarah,\n\nWe're pushing promo for the April 15 session this week — already 2,400 RSVPs. Format will be 20 min conversation + 40 min live Q&A from the audience.\n\nI'll send suggested discussion questions by April 5.\n\nMarcus", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'cm4a_c', channel: 'email', needs_response: false },
    ],
    alerts: [{ type: 'event_approaching', label: 'LinkedIn Live Apr 15 — prep questions not yet received', severity: 'medium' }],
  },


]

// ─── Review Queue Mock Data ───────────────────────────────────────────────────

export const MOCK_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: 'r1',
    received_at: '2026-03-30T07:55:00Z',
    from_name: 'Keisha Drummond',
    from_email: 'kdrummond@blackrock.com',
    subject: "Speaker Inquiry — BlackRock Women's Leadership Forum (Oct)",
    body_preview: "Hi, I'm Keisha Drummond, Head of Talent Development at BlackRock. We had an exceptional experience with Dr. Taheripour at our March forum and would love to have her back for our October session. Could we discuss availability?",
    account: 'team@moritaheripour.com',
    ai_confidence: 0.97,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Repeat client inquiry — past engagement on file. High confidence new opportunity. October timeframe gives good runway.',
  },
  {
    id: 'r2',
    received_at: '2026-03-30T09:15:00Z',
    from_name: 'Tom Ridley',
    from_email: 'tridley@hbr.org',
    subject: 'Harvard Business Review — Feature Collaboration',
    body_preview: "Following up on our earlier note — we'd love to explore a feature piece or podcast appearance with Dr. Taheripour around her negotiation framework and the themes from Bring Yourself. Would she be open to a brief call?",
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.62,
    state: 'needs_review',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Media/PR opportunity — not a speaking engagement but potentially high value for brand. Lower confidence due to ambiguous scope and no fee attached.',
  },
  {
    id: 'r3',
    received_at: '2026-03-29T16:45:00Z',
    from_name: 'Mailchimp',
    from_email: 'noreply@mailchimp.com',
    subject: 'Your March campaign report is ready',
    body_preview: 'Your March newsletter reached 4,823 subscribers with a 34% open rate and 6.1% click rate — your highest engagement month this year...',
    account: 'team@moritaheripour.com',
    ai_confidence: 0.99,
    state: 'ai_sorted',
    ai_suggested_action: 'ignore',
    ai_reasoning: 'Automated Mailchimp report. No action required.',
  },
  {
    id: 'r4',
    received_at: '2026-03-29T11:20:00Z',
    from_name: 'Priya Mehta',
    from_email: 'pmehta@mckinsey.com',
    subject: 'McKinsey Global Leadership Summit — Availability Check',
    body_preview: "Hello, our events team is building the speaker roster for the McKinsey Global Leadership Summit in September 2026. Dr. Taheripour is at the top of our list for a keynote on negotiation. Could you confirm availability and share current rates?",
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.93,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Clear availability and rate inquiry from named McKinsey contact with specific event timeline. High-value opportunity.',
  },
  {
    id: 'r5',
    received_at: '2026-03-29T08:10:00Z',
    from_name: 'David Koslowski',
    from_email: 'dkoslowski@vistage.com',
    subject: 'Re: Vistage Summit — One More Ask',
    body_preview: "Hi, I wanted to follow up one more time on the fee discussion. Our board reviewed and unfortunately can't go above $22k. I know this isn't what you're looking for — is there truly no flexibility? We're huge fans of Dr. Taheripour's work.",
    account: 'team@moritaheripour.com',
    ai_confidence: 0.55,
    state: 'needs_review',
    ai_suggested_action: 'update_prospect',
    ai_reasoning: 'Follow-up on existing fee negotiation with Vistage (prospect e3). Client is pushing back again on price — decision needed on whether to hold firm or offer alternative. Human judgment required.',
  },
  {
    id: 'r6',
    received_at: '2026-03-28T15:30:00Z',
    from_name: 'Google Alerts',
    from_email: 'googlealerts-noreply@google.com',
    subject: 'Google Alert — "Mori Taheripour"',
    body_preview: 'New mentions: (1) Forbes.com: "10 Negotiation Experts to Watch in 2026" — Dr. Taheripour ranked #4. (2) LinkedIn: Post shared 847 times from her recent article on authentic leadership...',
    account: 'team@moritaheripour.com',
    ai_confidence: 0.96,
    state: 'ai_sorted',
    ai_suggested_action: 'ignore',
    ai_reasoning: 'Automated Google Alert. Positive press mentions — no action required, but may be worth sharing with Mori.',
  },
]

// ─── Mock Companies ───────────────────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'co1', name: 'Microsoft', industry: 'Technology', website: 'microsoft.com',
    watching: false,
    teams: [{ id: 't1', name: 'Global Learning & Development' }],
    engagement_ids: ['e2'], contact_ids: ['c2a', 'c2b'],
    notes: 'Via Keppler Speakers. Budget approval pending. Lauren is enthusiastic.',
  },
  {
    id: 'co2', name: 'Deloitte US', industry: 'Professional Services', website: 'deloitte.com',
    watching: true,
    teams: [{ id: 't2', name: 'Leadership Forum' }, { id: 't3', name: 'People & Culture' }],
    engagement_ids: ['e4'], contact_ids: ['c4a', 'c4b', 'c4c'],
    notes: 'Strong relationship with CPO Marcus Webb. Contract in legal review — addendum coming.',
  },
  {
    id: 'co3', name: 'Wharton Executive Education', industry: 'Education', website: 'wharton.upenn.edu',
    watching: true,
    teams: [{ id: 't4', name: 'Executive Education' }, { id: 't5', name: "Women's Leadership" }],
    engagement_ids: ['e5'], contact_ids: ['c5a'],
    notes: 'Repeat client — third engagement. Rachel Simmons is primary. Advance sheet overdue.',
  },
  {
    id: 'co4', name: 'JPMorgan Chase', industry: 'Financial Services', website: 'jpmorgan.com',
    watching: false,
    teams: [{ id: 't6', name: "Women's Network" }],
    engagement_ids: ['e6'], contact_ids: ['c6a', 'c6b'],
    notes: 'Event Apr 22 — 23 days out, fully locked. Referred BlackRock.',
  },
  {
    id: 'co5', name: 'Vistage Worldwide', industry: 'Executive Coaching', website: 'vistage.com',
    watching: true,
    teams: [],
    engagement_ids: ['e3'], contact_ids: ['c3a', 'c3b'],
    notes: 'Fee negotiation ongoing. Holding at $25k. David pushing back again this week.',
  },
  {
    id: 'co6', name: 'Accenture', industry: 'Professional Services', website: 'accenture.com',
    watching: false,
    teams: [{ id: 't7', name: 'Inclusion & Diversity' }],
    engagement_ids: ['e1'], contact_ids: ['c1a'],
    notes: 'Fresh inbound today. Needs response.',
  },
  {
    id: 'co7', name: 'TechCorp', industry: 'Technology', website: 'techcorp.io',
    watching: false,
    teams: [],
    engagement_ids: ['e7'], contact_ids: ['c7a'],
    notes: 'Invoice 3 days overdue — Stephanie says payment releasing Apr 4.',
  },
  {
    id: 'co8', name: 'Goldman Sachs', industry: 'Financial Services', website: 'goldmansachs.com',
    watching: true,
    teams: [{ id: 't8', name: 'Leadership Accelerator' }],
    engagement_ids: ['e8'], contact_ids: ['c8a'],
    notes: 'Third engagement — always flawless. James hinting at October repeat.',
  },
  {
    id: 'co9',  name: 'Nike',        industry: 'Sports & Retail',      website: 'nike.com',          watching: false, teams: [],                                                  engagement_ids: ['e9'],       contact_ids: ['c9a'],          notes: 'Inquiry came in Friday. Portland offsite Jun 9.' },
  {
    id: 'co10', name: 'Salesforce',  industry: 'Technology',            website: 'salesforce.com',    watching: false, teams: [{ id: 't9', name: 'Sales Leadership' }],            engagement_ids: ['e10'],      contact_ids: ['c10a'],         notes: 'First outreach Mar 26. No response.' },
  {
    id: 'co11', name: 'Mayo Clinic', industry: 'Healthcare',            website: 'mayo.edu',          watching: true,  teams: [{ id: 't10', name: 'Leadership Program' }],         engagement_ids: ['e11'],      contact_ids: ['c11a'],         notes: 'Goldman referral. First touch sent. High potential.' },
  {
    id: 'co12', name: 'Amazon',      industry: 'Technology',            website: 'amazon.com',        watching: true,  teams: [{ id: 't11', name: 'Global L&D' }],                engagement_ids: ['e12'],      contact_ids: ['c12a', 'c12b'], notes: 'Large hybrid — 800 attendees. Patricia is the real decision maker.' },
  {
    id: 'co13', name: 'PwC',         industry: 'Professional Services', website: 'pwc.com',           watching: false, teams: [{ id: 't12', name: 'Partners Summit' }],            engagement_ids: ['e13'],      contact_ids: ['c13a'],         notes: 'Diana confirmed 90-min format. Ready for contract.' },
  {
    id: 'co14', name: 'Citi',        industry: 'Financial Services',    website: 'citi.com',          watching: false, teams: [{ id: 't13', name: 'Women in Finance' }],           engagement_ids: ['e14'],      contact_ids: ['c14a', 'c14b'], notes: 'Proposal sent. CFO sign-off expected by Friday.' },
  {
    id: 'co15', name: 'Stanford GSB',industry: 'Education',             website: 'gsb.stanford.edu',  watching: true,  teams: [{ id: 't14', name: 'Executive Programs' }],         engagement_ids: ['e15'],      contact_ids: ['c15a', 'c15b'], notes: 'Event Tuesday Apr 1. Elena confirmed, Chris handling day-of.' },
  {
    id: 'co16', name: 'BlackRock',   industry: 'Financial Services',    website: 'blackrock.com',     watching: true,  teams: [{ id: 't15', name: "Women's Leadership" }],         engagement_ids: ['e16'],      contact_ids: ['c16a'],         notes: 'Mar 12 event — complete and paid. Keisha already reaching out about October.' },
  { id: 'co17', name: 'NPR / How I Built This', industry: 'Media',            website: 'npr.org',         watching: true,  teams: [],                                               engagement_ids: ['em1'], contact_ids: ['cm1a_c'],  notes: 'Pre-call scheduled Apr 2. Topic angle in discussion.' },
  { id: 'co18', name: 'World Economic Forum',   industry: 'Nonprofit / Policy', website: 'weforum.org',     watching: true,  teams: [{ id: 't16', name: 'Leadership Series' }],       engagement_ids: ['em2'], contact_ids: ['cm2a_c'],  notes: 'Panel May 6 confirmed. Tech check not yet scheduled.' },
  { id: 'co19', name: 'Forbes',                 industry: 'Media',              website: 'forbes.com',      watching: true,  teams: [{ id: 't17', name: 'Leadership Editorial' }],    engagement_ids: ['em3'], contact_ids: ['cm3a_c'],  notes: 'Feature published Mar 18. Rachel asking about follow-up.' },
  { id: 'co20', name: 'LinkedIn',               industry: 'Technology / Media', website: 'linkedin.com',    watching: false, teams: [{ id: 't18', name: 'Creator Partnerships' }],    engagement_ids: ['em4'], contact_ids: ['cm4a_c'],  notes: 'LinkedIn Live Apr 15 — 2,400 RSVPs already.' },
]

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: TeamUser[] = [
  {
    id: 'u1', name: 'Mori Taheripour', email: 'mori@moritaheripour.com',
    role: 'admin', account: 'mori@moritaheripour.com', avatar_initials: 'MT',
  },
  {
    id: 'u2', name: 'Ryan G.', email: 'team@moritaheripour.com',
    role: 'admin', account: 'team@moritaheripour.com', avatar_initials: 'RG',
  },
  {
    id: 'u3', name: 'Sarah K.', email: 'booking@moritaheripour.com',
    role: 'regular', account: 'booking@moritaheripour.com', avatar_initials: 'SK',
  },
  {
    id: 'u4', name: 'James L.', email: 'assistant@moritaheripour.com',
    role: 'regular', account: 'assistant@moritaheripour.com', avatar_initials: 'JL',
  },
]