import { Engagement, EngagementAlert, ReviewItem, Company, TeamUser } from '@/types'

function noResponse(since: string): EngagementAlert {
  return { type: 'no_response', label: `No reply in 48h — since ${since}`, severity: 'high', since }
}
function followUp(since: string): EngagementAlert {
  return { type: 'follow_up_due', label: `Sent ${since} — time to follow up`, severity: 'medium', since }
}
function eventApproaching(label: string): EngagementAlert {
  return { type: 'event_approaching', label, severity: 'high' }
}
function invoiceOverdue(): EngagementAlert {
  return { type: 'invoice_overdue', label: 'Invoice unpaid — 32 days outstanding', severity: 'high' }
}

export const MOCK_ENGAGEMENTS: Engagement[] = [

  // ── PROSPECTS ──────────────────────────────────────────────────────────────

  // inquiry — came in this morning, no response yet
  {
    id: 'e1',
    created_at: '2026-03-30T08:45:00Z',
    updated_at: '2026-03-30T08:45:00Z',
    last_activity_at: '2026-03-30T08:45:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Accenture',
    source: 'Website inquiry',
    contacts: [{ id: 'c1a', first_name: 'Anika', last_name: 'Thomas', email: 'anika.thomas@accenture.com', title: 'VP Inclusion & Diversity', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Inclusive Negotiation Practices',
    event_format: 'virtual', audience_size: 250,
    proposed_dates: [{ date: '2026-07-14', times: ['10–11am EST', '2–3pm EST'] }, { date: '2026-07-21', times: ['10–11am EST'] }, { date: '2026-08-11' }],
    notes: 'Inbound this morning via website contact form. Interested in Q3 virtual workshop for underrepresented talent.',
    comms: [{
      id: 'cm1a', type: 'email_inbound', date: '2026-03-30T08:45:00Z',
      subject: 'Speaking Inquiry — Inclusion & Negotiation Workshop',
      body: "Hello,\n\nI'm the VP of Inclusion & Diversity at Accenture and came across Mori's work through her Wharton profile. Her approach to negotiation resonated deeply with our current programming goals.\n\nWe're planning a virtual workshop in Q3 focused on helping underrepresented talent negotiate more effectively in corporate settings. Would she be available for a 60-90 minute session?\n\nWarm regards,\nAnika Thomas\nVP, Inclusion & Diversity\nAccenture",
      from_name: 'Anika Thomas', to_name: "Mori's Team", contact_id: 'c1a', channel: 'email', needs_response: true, response_due_by: '2026-04-05T14:00:00Z',
    }],
    alerts: [noResponse('Mar 31')],
  },

  // inquiry — came in Wednesday, still waiting on response
  {
    id: 'e9',
    created_at: '2026-03-30T14:30:00Z',
    updated_at: '2026-03-30T14:30:00Z',
    last_activity_at: '2026-03-30T14:30:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Nike',
    source: 'Direct inquiry',
    contacts: [{ id: 'c9a', first_name: 'Tanya', last_name: 'Rhodes', email: 'trhodes@nike.com', title: 'Director of Leadership Development', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Negotiation & Influence for Executives',
    event_format: 'in_person', audience_size: 200,
    event_date: '2026-06-09', event_city: 'Portland, OR',
    notes: 'Came in Wednesday. Senior leadership offsite, June in Portland. No response yet — needs reply today.',
    comms: [{
      id: 'cm9a', type: 'email_inbound', date: '2026-03-30T14:30:00Z',
      subject: 'Speaking Inquiry — Nike Executive Leadership Offsite',
      body: "Hi,\n\nMy name is Tanya Rhodes and I lead Leadership Development at Nike. We're planning an executive offsite in early June in Portland and Mori's work came highly recommended by a colleague at Wharton.\n\nWe're looking for a half-day keynote and workshop on negotiation and influence — ideally tailored for senior leaders. Could you share availability and rates?\n\nBest,\nTanya",
      from_name: 'Tanya Rhodes', to_name: "Mori's Team", contact_id: 'c9a', channel: 'email', needs_response: true, response_due_by: '2026-03-30T00:00:00Z',
    }],
    alerts: [noResponse('Mar 31')],
  },

  // outreach — team reached out Monday, no reply yet
  {
    id: 'e10',
    created_at: '2026-03-26T11:00:00Z',
    updated_at: '2026-03-26T11:00:00Z',
    last_activity_at: '2026-03-26T11:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Salesforce',
    source: 'Outreach by team',
    contacts: [{ id: 'c10a', first_name: 'Marcus', last_name: 'Lin', email: 'mlin@salesforce.com', title: 'VP People & Culture', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'The Art of Negotiation for Sales Leaders',
    event_format: 'virtual', audience_size: 500,
    event_date: '2026-06-18', event_city: 'Virtual',
    notes: 'EA identified as strong fit — Salesforce runs a large virtual summit in June. No response in 6 days.',
    comms: [{
      id: 'cm10a', type: 'email_outbound', date: '2026-03-26T11:00:00Z',
      subject: 'Speaker Introduction — Mori Taheripour',
      body: "Hi Marcus,\n\nWe're reaching out on behalf of Mori Taheripour, Wharton professor and author of Bring Yourself. We believe her work on negotiation would resonate strongly with your sales leadership community.\n\nShe's available for your June summit and would love to connect. I've attached her speaker profile for reference.\n\nWould you be open to a brief call?\n\nBest,\nSarah K.\nBooking, Mori Taheripour",
      from_name: "Mori's Team", to_name: 'Marcus Lin', contact_id: 'c10a', staff_name: 'Sarah K.', channel: 'email', needs_response: false,
    }],
    alerts: [followUp('Mar 31')],
  },

  // outreach — referral-based, high potential, first touch sent last week
  {
    id: 'e11',
    created_at: '2026-03-26T14:00:00Z',
    updated_at: '2026-03-26T14:00:00Z',
    last_activity_at: '2026-03-26T14:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Mayo Clinic',
    source: 'Referral from Goldman Sachs',
    contacts: [{ id: 'c11a', first_name: 'Sarah', last_name: 'Okonkwo', email: 'sokonkwo@mayo.edu', title: 'Chief Human Resources Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true }],
    topic: 'Negotiation & Difficult Conversations for Healthcare Leaders',
    event_format: 'in_person', audience_size: 150,
    event_city: 'Rochester, MN',
    notes: 'Warm referral from James Okafor at Goldman. Sarah is the CHRO — high-quality lead. First touch sent last Friday.',
    comms: [{
      id: 'cm11a', type: 'email_outbound', date: '2026-03-26T14:00:00Z',
      subject: 'Introduction — Mori Taheripour (via James Okafor, Goldman Sachs)',
      body: "Hi Sarah,\n\nJames Okafor at Goldman Sachs suggested I reach out. He spoke highly of Mori Taheripour's session with their leadership team and felt her work would resonate deeply with Mayo Clinic's leadership programs.\n\nMori is a Wharton professor and author who specializes in negotiation and difficult conversations — with a particular focus on high-stakes, relationship-driven environments.\n\nWould you have 20 minutes for a brief call?\n\nBest,\nRyan G.",
      from_name: "Mori's Team", to_name: 'Sarah Okonkwo', contact_id: 'c11a', staff_name: 'Ryan G.', channel: 'email', needs_response: false,
    }],
    alerts: [followUp('Mar 29')],
  },

  // in_contact — bureau intro, had a call, awaiting follow-up
  {
    id: 'e2',
    created_at: '2026-03-21T10:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
    last_activity_at: '2026-03-30T10:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Microsoft',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [
      { id: 'c2a', first_name: 'Lauren', last_name: 'Prescott', email: 'lprescott@microsoft.com', title: 'Director, Global Learning', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c2b', first_name: 'James', last_name: 'Hollis', email: 'jhollis@kepplerspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Microsoft LEAP Leadership Summit',
    event_date: '2026-09-10',
    event_location: 'Microsoft Campus', event_city: 'Redmond, WA',
    event_format: 'in_person', audience_size: 300,
    topic: 'The Negotiation Mindset', session_length: 60, fee: 26000,
    travel_covered: true, hotel_covered: true,
    notes: 'Good intro call Mar 21 with Lauren. Enthusiastic but waiting on internal budget sign-off. Sent follow-up March 31.',
    comms: [
      { id: 'cm2a', type: 'email_inbound', date: '2026-03-21T09:00:00Z', subject: 'Microsoft LEAP Summit — Speaker Inquiry', body: 'Initial outreach via Keppler. Microsoft interested in a keynote for their LEAP program leadership summit in September.', from_name: 'James Hollis', to_name: "Mori's Team", contact_id: 'c2b', channel: 'email', needs_response: false },
      { id: 'cm2b', type: 'call', date: '2026-03-21T14:00:00Z', subject: 'Intro call with Lauren Prescott — 30 min', body: "Great call. Lauren is a big fan of Bring Yourself and already has a topic in mind. Budget approval is the only hurdle — she expects to hear back from her VP by end of month.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm2c', type: 'email_outbound', date: '2026-03-30T10:00:00Z', subject: "Re: Microsoft LEAP — Next Steps", body: "Hi Lauren,\n\nGreat connecting last week. I wanted to follow up and see if there's any update on budget approval. We're happy to hold the Sep 11 date while you finalize internally.\n\nLet me know if you need any additional materials.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Lauren Prescott', contact_id: 'c2a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
    ],
    calls: [
      { id: 'call_e2_1', type: 'discovery', status: 'completed', number: 1, requested_at: '2026-03-19T14:00:00Z', scheduled_at: '2026-03-21T14:00:00Z', completed_at: '2026-03-21T14:00:00Z', notes: 'Great call with Lauren — enthusiastic, budget approval the only hurdle.', added_by: 'manual' },
      { id: 'call_e2_2', type: 'mori', status: 'requested', number: 1, requested_at: '2026-04-01T10:00:00Z', added_by: 'manual' },
    ],
    alerts: [followUp('Mar 31')],
  },

  // in_contact — multi-contact, active thread, speaker packet sent this week
  {
    id: 'e12',
    created_at: '2026-03-19T09:00:00Z',
    updated_at: '2026-03-30T16:00:00Z',
    last_activity_at: '2026-03-30T16:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Amazon',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c12a', first_name: 'Patricia', last_name: 'Yuen', email: 'pyuen@amazon.com', title: 'Global Head of L&D', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c12b', first_name: 'Carlos', last_name: 'Mendes', email: 'cmendes@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    topic: 'Inclusive Leadership & Negotiation',
    event_format: 'hybrid', audience_size: 800,
    event_date: '2026-08-20', event_city: 'Seattle, WA',
    fee: 32000, travel_covered: true, hotel_covered: true,
    notes: 'Large hybrid event — 800 attendees in-person + virtual. Patricia is the real decision maker. Speaker packet sent yesterday.',
    comms: [
      { id: 'cm12a', type: 'email_inbound', date: '2026-03-19T09:00:00Z', subject: 'Amazon Leadership Conference — Speaker Inquiry', body: 'Via Washington Speakers Bureau. Patricia Yuen at Amazon interested in Mori for their annual leadership conference in August.', from_name: 'Carlos Mendes', to_name: "Mori's Team", contact_id: 'c12b', channel: 'email', needs_response: false },
      { id: 'cm12b', type: 'call', date: '2026-03-25T15:00:00Z', subject: 'Intro call with Patricia Yuen — 45 min', body: "Excellent call. Patricia has read Bring Yourself and came with prepared questions. She wants a hybrid format with breakout components. Patricia said she'll push this through internally.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm12c', type: 'email_outbound', date: '2026-03-30T16:00:00Z', subject: 'Re: Amazon Leadership Conference — Speaker Packet + Hybrid Format Notes', body: "Hi Patricia,\n\nReally enjoyed our conversation last week. As discussed, I'm attaching Mori's full speaker packet along with some notes on how she's structured hybrid keynotes in the past — including the Q&A and breakout components.\n\nLet us know when you'd like to connect again.\n\nBest,\nRyan G.", from_name: "Mori's Team", to_name: 'Patricia Yuen', contact_id: 'c12a', staff_name: 'Ryan G.', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // discussing — fee negotiation actively happening
  {
    id: 'e3',
    created_at: '2026-03-16T10:00:00Z',
    updated_at: '2026-03-30T09:00:00Z',
    last_activity_at: '2026-03-30T09:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Vistage Worldwide',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c3a', first_name: 'David', last_name: 'Koslowski', email: 'dkoslowski@vistage.com', title: 'Program Director', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true },
      { id: 'c3b', first_name: 'Nina', last_name: 'Okafor', email: 'nokafor@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Vistage CEO Peer Group Summit',
    event_date: '2026-07-22',
    event_location: 'Marriott Marquis', event_city: 'Chicago, IL',
    event_format: 'in_person', audience_size: 120,
    topic: 'Navigating Difficult Conversations as a CEO',
    session_length: 90, fee: 25000,
    travel_covered: true, hotel_covered: true,
    notes: 'Three rounds of back-and-forth on fee. David keeps coming back at $22k for 90 min. Holding firm at $25k — Nina agrees this is the right move.',
    comms: [
      { id: 'cm3a', type: 'email_inbound', date: '2026-03-16T10:00:00Z', subject: 'Vistage CEO Summit — Speaker Inquiry', body: 'Via Washington Speakers Bureau. Interested in Mori for July CEO summit in Chicago.', from_name: 'Nina Okafor', to_name: "Mori's Team", contact_id: 'c3b', channel: 'email', needs_response: false },
      { id: 'cm3b', type: 'call', date: '2026-03-19T13:00:00Z', subject: 'Discovery call — 25 min', body: 'Good call with David. Very interested in the topic. Fee will be the sticking point — he already mentioned budget constraints.', from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm3c', type: 'email_outbound', date: '2026-03-21T09:00:00Z', subject: 'Re: Vistage Summit — Proposal', body: 'Sent formal proposal: 90 min keynote + Q&A at $25,000. Travel and hotel required.', from_name: "Mori's Team", to_name: 'David Koslowski', contact_id: 'c3a', staff_name: 'EA', channel: 'email', needs_response: false },
      { id: 'cm3d', type: 'email_inbound', date: '2026-03-26T11:00:00Z', subject: 'Re: Vistage Summit — Counter Proposal', body: "Hi, we appreciate the proposal. Our budget for this session tops out at $22,000 — is there any flexibility? Happy to discuss.", from_name: 'David Koslowski', to_name: "Mori's Team", contact_id: 'c3a', channel: 'email', needs_response: false },
      { id: 'cm3e', type: 'email_outbound', date: '2026-03-27T10:00:00Z', subject: 'Re: Vistage Summit — Response to Counter', body: "Hi David,\n\nThank you for coming back to us. We've reviewed your counter and unfortunately aren't able to move on the fee for a 90-minute engagement. Mori's rate for this format is $25,000.\n\nWe could offer a 60-minute keynote at $20,000 if that's more workable — the session would still be comprehensive but more tightly structured.\n\nLet us know how you'd like to proceed.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'David Koslowski', contact_id: 'c3a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm3f', type: 'email_inbound', date: '2026-03-30T09:00:00Z', subject: 'Re: Vistage Summit — One More Ask', body: "We still prefer the 90-minute format. Our board reviewed and unfortunately can't go above $22k. I know this isn't what you're looking for — is there truly no flexibility? We're huge fans of Mori's work.", from_name: 'David Koslowski', to_name: "Mori's Team", contact_id: 'c3a', channel: 'email', needs_response: true, response_due_by: '2026-03-30T00:00:00Z' },
    ],
    alerts: [noResponse('Mar 31')],
  },

  // discussing — ready to move to contract, needs agreement sent
  {
    id: 'e13',
    created_at: '2026-03-13T10:00:00Z',
    updated_at: '2026-03-30T14:00:00Z',
    last_activity_at: '2026-03-30T14:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'PwC',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c13a', first_name: 'Diana', last_name: 'Nakamura', email: 'diana.nakamura@pwc.com', title: 'Chief Talent Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
    ],
    topic: 'Negotiation Strategy for Professional Services',
    event_format: 'in_person', audience_size: 300,
    event_date: '2026-06-25', event_city: 'New York, NY',
    fee: 24000, travel_covered: true, hotel_covered: false,
    notes: 'Diana confirmed 90-minute format Mar 25. Contract needs to be drafted and sent — sitting idle for 8 days.',
    comms: [
      { id: 'cm13a', type: 'email_inbound', date: '2026-03-13T10:00:00Z', subject: 'PwC Partners Summit — Speaker Inquiry', body: 'Inquiry via Premier Speakers. Interested in June date for PwC annual partners summit in NYC.', from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: false },
      { id: 'cm13b', type: 'call', date: '2026-03-19T11:00:00Z', subject: 'Discovery call — 30 min', body: "Strong chemistry. Diana is a former Wharton student and already knows Mori's work. Very aligned on topic. Only question is format — 60 vs 90 min.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm13c', type: 'email_outbound', date: '2026-03-23T09:00:00Z', subject: 'Re: PwC Partners Summit — Format Options', body: "Sent Diana a breakdown of both format options with sample agendas for each.", from_name: "Mori's Team", to_name: 'Diana Nakamura', contact_id: 'c13a', staff_name: 'EA', channel: 'email', needs_response: false },
      { id: 'cm13d', type: 'email_inbound', date: '2026-03-25T14:00:00Z', subject: 'Re: PwC Partners Summit — Confirmed: 90-Minute Format', body: "Hi,\n\nAfter reviewing the sample agendas we'd like to move forward with the 90-minute deep-dive format. Can you send over a draft agreement and confirm the fee?\n\nLooking forward to working with Mori.\n\nDiana", from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // discussing — formal proposal sent, CFO sign-off confirmed
  {
    id: 'e14',
    created_at: '2026-03-06T09:00:00Z',
    updated_at: '2026-03-30T14:00:00Z',
    last_activity_at: '2026-03-30T14:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Citi',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [
      { id: 'c14a', first_name: 'Nadia', last_name: 'Hassan', email: 'nhassan@citi.com', title: 'Managing Director, Talent & OD', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c14b', first_name: 'Erin', last_name: 'Cho', email: 'echo@kepplerspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Citi Women in Finance Leadership Day',
    event_date: '2026-05-29',
    event_location: '388 Greenwich St', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 175,
    topic: 'Negotiating Your Career: Strategies for Women in Finance',
    session_length: 60, fee: 23000,
    travel_covered: false, hotel_covered: false,
    notes: 'Proposal sent Mar 26. Nadia confirmed CFO sign-off came through yesterday. Expecting formal confirmation today or tomorrow.',
    comms: [
      { id: 'cm14a', type: 'email_inbound', date: '2026-03-06T09:00:00Z', subject: 'Citi Women in Finance — Speaker Inquiry', body: 'Via Keppler. Nadia Hassan at Citi interested in a keynote for their Women in Finance Leadership Day in late May.', from_name: 'Erin Cho', to_name: "Mori's Team", contact_id: 'c14b', channel: 'email', needs_response: false },
      { id: 'cm14b', type: 'call', date: '2026-03-13T11:00:00Z', subject: 'Intro call with Nadia — 30 min', body: "Good call. Nadia very engaged, has attended Mori's sessions before at Wharton executive ed. Fast mover — wants to finalize quickly.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm14c', type: 'email_outbound', date: '2026-03-26T09:00:00Z', subject: 'Citi Women in Finance — Formal Proposal', body: "Hi Nadia,\n\nThank you for the great conversation earlier this month. I'm pleased to send over a formal proposal for Mori's keynote at your Women in Finance Leadership Day on May 30.\n\nPlease find attached: speaker brief, session outline, and fee agreement. We look forward to your confirmation.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Nadia Hassan', contact_id: 'c14a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm14d', type: 'email_inbound', date: '2026-03-30T14:00:00Z', subject: 'Re: Citi Women in Finance — CFO Sign-Off Confirmed', body: "Hi Sarah,\n\nGreat news — CFO approved. I'll be sending formal sign-off today or first thing tomorrow. We're very excited to have Mori.\n\nNadia", from_name: 'Nadia Hassan', to_name: "Mori's Team", contact_id: 'c14a', channel: 'email', needs_response: false },
    ],
    calls: [
      { id: 'call_e13_1', type: 'discovery', status: 'completed', number: 1, requested_at: '2026-03-16T09:00:00Z', scheduled_at: '2026-03-18T11:00:00Z', completed_at: '2026-03-18T11:00:00Z', notes: 'Strong chemistry — Diana is a former Wharton student.', added_by: 'manual' },
      { id: 'call_e13_2', type: 'mori', status: 'completed', number: 1, requested_at: '2026-03-19T10:00:00Z', scheduled_at: '2026-03-22T14:00:00Z', completed_at: '2026-03-22T14:00:00Z', notes: 'Mori and Diana connected directly — confirmed 90-min format.', added_by: 'manual' },
    ],
    alerts: [],
  },

  // ── ENGAGEMENTS ────────────────────────────────────────────────────────────

  // TODAY — happening today April 3, fully ready
  {
    id: 'e17',
    created_at: '2026-01-21T09:00:00Z',
    updated_at: '2026-03-30T15:00:00Z',
    last_activity_at: '2026-03-30T15:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'client_deliverables_sent', 'advance_sheet_complete'],
    post_event_flags: [],
    organization: 'Wharton Executive Education',
    source: 'Repeat client',
    event_time: '10am – 11:15am',
    contacts: [
      { id: 'c17a', first_name: 'Rachel', last_name: 'Simmons', email: 'rsimmons@wharton.upenn.edu', phone: '215-555-0101', title: 'Director of Executive Education', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true, notes: 'Fourth engagement with Mori. Rachel is always early to respond. Prefers email.' },
      { id: 'c17b', first_name: 'Chris', last_name: 'Park', email: 'cpark@wharton.upenn.edu', title: 'Events Coordinator', role: 'assistant', is_current_point_of_contact: false, notes: 'Managing day-of logistics. Confirmed 8:30am setup call.' },
    ],
    event_name: 'Women in Leadership Summit 2026',
    event_date: '2026-04-04',
    event_location: 'Huntsman Hall, Room 300', event_city: 'Philadelphia, PA',
    event_format: 'in_person', audience_size: 250,
    topic: 'Negotiation & Influence for Executive Women',
    session_length: 75, fee: 22000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Lapel mic, clicker, HDMI, confidence monitor, recording setup',
    notes: "Today's event. Everything fully confirmed — Rachel signed off last week. Chris confirmed AV check at 8:30am. Mori is speaking at 10am.",
    comms: [
      { id: 'cm17a', type: 'email_outbound', date: '2026-02-16T10:00:00Z', subject: 'Women in Leadership Summit — Speaking Agreement', body: "Hi Rachel,\n\nSo glad to be working together again. Please find attached the speaking agreement for April 1.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Rachel Simmons', contact_id: 'c17a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm17b', type: 'email_inbound', date: '2026-02-19T09:00:00Z', subject: 'Re: Women in Leadership Summit — Contract Signed', body: "Signed and returned — so excited to have Mori back for a fourth year. She's always the highlight of the summit.\n\nRachel", from_name: 'Rachel Simmons', to_name: "Mori's Team", contact_id: 'c17a', channel: 'email', needs_response: false },
      { id: 'cm17c', type: 'email_outbound', date: '2026-03-21T09:00:00Z', subject: 'Women in Leadership Summit — Briefing Document', body: "Hi Rachel,\n\nAttached is the briefing document for April 1. Please review and confirm everything looks accurate.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Rachel Simmons', contact_id: 'c17a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm17d', type: 'email_inbound', date: '2026-03-23T10:00:00Z', subject: 'Re: Women in Leadership Summit — Briefing Document Confirmed', body: "Everything looks perfect. Final headcount is 247. Chris will handle the AV check at 8:30am — Mori is on at 10am sharp.\n\nRachel", from_name: 'Rachel Simmons', to_name: "Mori's Team", contact_id: 'c17a', channel: 'email', needs_response: false },
      { id: 'cm17e', type: 'email_inbound', date: '2026-03-30T15:00:00Z', subject: "Women in Leadership — See You Today!", body: "Hi,\n\nJust confirming everything is set for this morning. Chris will be in the lobby of Huntsman Hall at 8:30am. We're all very excited.\n\nRachel", from_name: 'Rachel Simmons', to_name: "Mori's Team", contact_id: 'c17a', channel: 'email', needs_response: false },
    ],
    alerts: [eventApproaching("Today — Wharton Women in Leadership, 10am in Philadelphia")],
  },

  // contract_sent — legal holding it up
  {
    id: 'e4',
    created_at: '2026-03-02T09:00:00Z',
    updated_at: '2026-03-30T09:15:00Z',
    last_activity_at: '2026-03-30T09:15:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent'],
    post_event_flags: [],
    organization: 'Deloitte US',
    event_time: 'TBD — awaiting logistics confirmation',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c4a', first_name: 'Marcus', last_name: 'Webb', email: 'marcus.webb@deloitte.com', phone: '212-555-0202', title: 'Chief People Officer', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c4b', first_name: 'Jennifer', last_name: 'Park', email: 'jennifer.park@deloitte.com', title: 'EA to CPO', role: 'assistant', is_current_point_of_contact: false, notes: 'Handles all logistics for Marcus. CC on every email.' },
      { id: 'c4c', first_name: 'David', last_name: 'Chen', email: 'dchen@deloitte-legal.com', title: 'Associate General Counsel', role: 'legal', is_current_point_of_contact: false, notes: 'Reviewed addendum — waiting on our sign-off' },
    ],
    event_name: 'Deloitte Leadership Forum 2026',
    event_date: '2026-05-08',
    event_location: 'Deloitte University', event_city: 'Westlake, TX',
    event_format: 'in_person', audience_size: 400,
    topic: 'The Art of Negotiation in High-Stakes Environments',
    session_length: 60, fee: 28000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Handheld mic preferred, full AV team on site, confidence monitor',
    notes: 'Contract sent Mar 21. Legal addendum came back this morning from Jennifer — needs review and sign-off today. Event April 15, 2 weeks out.',
    comms: [
      { id: 'cm4a', type: 'email_outbound', date: '2026-03-21T10:00:00Z', subject: 'Deloitte Leadership Forum 2026 — Speaking Agreement', body: "Hi Marcus,\n\nPlease find attached the speaking agreement for the Deloitte Leadership Forum on June 4. I've cc'd Jennifer on logistics.\n\nLet us know if you have any questions.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Marcus Webb', contact_id: 'c4a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm4b', type: 'email_inbound', date: '2026-03-26T14:00:00Z', subject: 'Re: Deloitte Leadership Forum — Legal Review', body: "Our legal team (David Chen, cc'd) has reviewed the agreement. Two items to address: IP clause and recording rights addendum. Nothing major.\n\nMarcus", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'c4a', channel: 'email', needs_response: false },
      { id: 'cm4c', type: 'call', date: '2026-03-28T10:00:00Z', subject: 'Legal review call with David Chen — 20 min', body: "Good call. Both issues are minor. David drafting a short addendum. Back to us by April 1.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm4d', type: 'email_inbound', date: '2026-03-30T09:15:00Z', subject: 'Re: Deloitte Leadership Forum — Addendum Ready for Review', body: "Hi,\n\nDavid has drafted the addendum — attached. Please review and let us know if the language works on your end. Once agreed, Marcus will sign the full agreement.\n\nJennifer Park\nEA to Marcus Webb", from_name: 'Jennifer Park', to_name: "Mori's Team", contact_id: 'c4b', channel: 'email', needs_response: true, response_due_by: '2026-04-05T00:00:00Z' },
    ],
    alerts: [noResponse('Mar 31')],
  },

  // contract_signed — briefing doc still needed
  {
    id: 'e5',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-03-26T14:00:00Z',
    last_activity_at: '2026-03-26T14:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'materials_requested'],
    post_event_flags: [],
    organization: 'Morgan Stanley',
    event_time: '9am – 10:15am',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [{
      id: 'c5a', first_name: 'Elena', last_name: 'Torres',
      email: 'etorres@morganstanley.com', phone: '212-555-0303',
      title: 'Head of Talent & Culture', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
      notes: 'New client — very organized. Prefers concise emails.',
    }],
    event_name: 'Morgan Stanley Women Forward Summit',
    event_date: '2026-04-09',
    event_location: '1585 Broadway', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 300,
    topic: 'Negotiation & Influence for Senior Women',
    session_length: 75, fee: 24000,
    travel_covered: false, hotel_covered: false,
    av_needs: 'Lapel mic, clicker, HDMI, confidence monitor, recording setup',
    notes: 'Elena requested bio and headshot on Apr 1. Not yet sent.',
    comms: [
      { id: 'cm5a', type: 'email_outbound', date: '2026-03-02T10:00:00Z', subject: 'Morgan Stanley Women Forward — Speaking Agreement', body: "Hi Elena,\n\nThank you for moving quickly on this. Please find attached the speaking agreement for April 9.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Elena Torres', contact_id: 'c5a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm5b', type: 'email_inbound', date: '2026-03-26T14:00:00Z', subject: 'Re: Morgan Stanley Women Forward — Contract Signed', body: "Hi Sarah,\n\nSigned and returned. Looking forward to working with Mori — let me know what you'll need for the briefing document.\n\nElena", from_name: 'Elena Torres', to_name: "Mori's Team", contact_id: 'c5a', channel: 'email', needs_response: false },
      { id: 'cm5c', type: 'email_inbound', date: '2026-04-01T10:00:00Z', subject: 'Morgan Stanley Women Forward — Materials Request', body: "Hi Sarah,\n\nAs we finalize the program, could you send over Mori's bio and a high-res headshot for the event materials? We're also putting together the run-of-show and would love a one-line speaker intro.\n\nElena", from_name: 'Elena Torres', to_name: "Mori's Team", contact_id: 'c5a', channel: 'email', needs_response: true },
    ],
    alerts: [eventApproaching('Event Apr 9 — client materials not yet received')],
  },

  // client_deliverables_sent — event in 19 days
  {
    id: 'e6',
    created_at: '2026-01-21T08:00:00Z',
    updated_at: '2026-03-29T11:00:00Z',
    last_activity_at: '2026-03-29T11:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_complete'],
    post_event_flags: [],
    organization: 'JPMorgan Chase',
    event_time: '10:15am – 11am',
    source: 'Direct outreach',
    contacts: [
      { id: 'c6a', first_name: 'Priya', last_name: 'Nair', email: 'priya.nair@jpmorgan.com', title: 'Managing Director, Talent', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c6b', first_name: 'Tom', last_name: 'Everett', email: 'tom.everett@jpmorgan.com', title: 'AV & Events Coordinator', role: 'av', is_current_point_of_contact: false, notes: 'Room confirmed — main auditorium, floor 2. AV check at 8:30am day of.' },
    ],
    event_name: "Chase Women's Network Annual Conference",
    event_date: '2026-04-05',
    event_location: '383 Madison Ave', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 182,
    topic: 'Negotiating Your Worth: Strategies for Senior Women',
    session_length: 45, fee: 18000,
    travel_covered: false, hotel_covered: false,
    av_needs: 'Podium mic, projector, no clicker needed — slides advanced by AV tech',
    notes: 'All set. Briefing doc confirmed, headcount locked at 182, run of show received. AV check 8:30am Apr 5.',
    comms: [
      { id: 'cm6a', type: 'email_outbound', date: '2026-03-11T09:00:00Z', subject: "Chase Women's Network — Briefing Document", body: "Hi Priya,\n\nAttached is the briefing document for the April 5 conference. Please review and confirm all details are accurate.\n\nAlso cc'ing Tom on AV logistics.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Priya Nair', contact_id: 'c6a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm6b', type: 'email_inbound', date: '2026-03-15T10:00:00Z', subject: "Re: Chase Women's Network — Briefing Document Confirmed", body: "All confirmed. One update: we've moved to the main auditorium on floor 2 — Tom will have everything set up. AV check is at 8:30am.\n\nCurrent headcount is 178. We're so excited to have Mori.\n\nPriya", from_name: 'Priya Nair', to_name: "Mori's Team", contact_id: 'c6a', channel: 'email', needs_response: false },
      { id: 'cm6c', type: 'email_inbound', date: '2026-03-29T11:00:00Z', subject: "Chase Conference — Final Headcount & Run of Show", body: "Final headcount confirmed at 182. Attached is the full run of show — Mori is on at 10:15am following opening remarks.\n\nPriya", from_name: 'Priya Nair', to_name: "Mori's Team", contact_id: 'c6a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // fully ready — LinkedIn Live in 12 days
  {
    id: 'em4',
    created_at: '2026-03-11T09:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
    last_activity_at: '2026-03-30T10:00:00Z',
    section: 'engagements',
    event_type: 'livestream',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent'],
    post_event_flags: [],
    organization: 'LinkedIn Live',
    event_time: '12pm ET – 1pm ET',
    source: 'LinkedIn editorial team',
    contacts: [{ id: 'cm4a_c', first_name: 'Marcus', last_name: 'Webb', email: 'mwebb@linkedin.com', title: 'Creator Partnerships Lead', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'LinkedIn Live — Negotiation Masterclass',
    event_date: '2026-04-10',
    event_format: 'virtual',
    audience_size: 10000,
    topic: 'Live Q&A: How to Negotiate Anything Without Losing Yourself',
    notes: 'LinkedIn Live April 10 — 7 days out. 2,400+ RSVPs already. Prep questions expected from Marcus by April 5.',
    comms: [
      { id: 'cm_em4a', type: 'email_inbound', date: '2026-03-11T09:00:00Z', subject: 'LinkedIn Live — Creator Feature Invitation', body: "Hi,\n\nWe're the LinkedIn Live editorial team and we'd love to feature Mori for a live negotiation masterclass on April 15. Expected audience: 8,000–12,000 live viewers plus replay.\n\nMarcus Webb\nCreator Partnerships, LinkedIn", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'cm4a_c', channel: 'email', needs_response: false },
      { id: 'cm_em4b', type: 'email_outbound', date: '2026-03-16T10:00:00Z', subject: 'Re: LinkedIn Live — Confirmed for April 15', body: "Hi Marcus,\n\nMori would love to participate — April 15 works perfectly. Attaching bio and headshot for promotional use.\n\nCould you send over the format details and any prep questions you'd like her to review in advance?\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Marcus Webb', contact_id: 'cm4a_c', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm_em4c', type: 'email_inbound', date: '2026-03-30T10:00:00Z', subject: 'LinkedIn Live — 2,400 RSVPs + Format Details', body: "Hi Sarah,\n\nWe're pushing promo for the April 15 session — already 2,400 RSVPs. Format will be 20 min conversation + 40 min live Q&A from the audience.\n\nI'll send suggested discussion questions by April 5.\n\nMarcus", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'cm4a_c', channel: 'email', needs_response: false },
    ],
    alerts: [{ type: 'event_approaching', label: 'LinkedIn Live Apr 10 — prep questions not yet received', severity: 'medium' }],
  },

  // ── POST-EVENT ─────────────────────────────────────────────────────────────

  // Stanford GSB — happened yesterday April 2, invoice needs to go out
  {
    id: 'e15',
    created_at: '2025-12-16T09:00:00Z',
    updated_at: '2026-03-30T18:00:00Z',
    last_activity_at: '2026-03-30T18:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'client_deliverables_sent', 'advance_sheet_complete'],
    post_event_flags: [],
    organization: 'Stanford Graduate School of Business',
    event_time: '9am – 11am',
    source: 'Direct — faculty referral',
    contacts: [
      { id: 'c15a', first_name: 'Elena', last_name: 'Vasquez', email: 'evasquez@gsb.stanford.edu', title: 'Director of Executive Programs', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true },
      { id: 'c15b', first_name: 'Chris', last_name: 'Tanaka', email: 'ctanaka@gsb.stanford.edu', title: 'Events Coordinator', role: 'assistant', is_current_point_of_contact: false, notes: 'Managed all day-of logistics.' },
    ],
    event_name: 'GSB Executive Leadership Program — Negotiation Module',
    event_date: '2026-03-30',
    event_location: 'Knight Management Center', event_city: 'Stanford, CA',
    event_format: 'in_person', audience_size: 60,
    topic: 'Bring Yourself: Authentic Negotiation for Executive Leaders',
    session_length: 120, fee: 30000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Lapel mic, HDMI, whiteboard, no slides — discussion format',
    notes: 'Happened yesterday — great session. Elena sent a glowing note. Invoice needs to go out today.',
    comms: [
      { id: 'cm15a', type: 'stage_change', date: '2026-01-11T11:00:00Z', subject: 'Contract signed', staff_name: 'Sarah K.', needs_response: false },
      { id: 'cm15b', type: 'email_outbound', date: '2026-03-16T09:00:00Z', subject: 'GSB Executive Program — Briefing Document', body: "Hi Elena,\n\nAttached is the briefing document for April 1. Please review and confirm everything is accurate.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Elena Vasquez', contact_id: 'c15a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm15c', type: 'email_inbound', date: '2026-03-19T10:00:00Z', subject: 'Re: GSB — Briefing Document Confirmed', body: "Everything looks perfect. Chris will handle day-of. The cohort is very excited — several participants have read Bring Yourself already.\n\nElena", from_name: 'Elena Vasquez', to_name: "Mori's Team", contact_id: 'c15a', channel: 'email', needs_response: false },
      { id: 'cm15d', type: 'email_inbound', date: '2026-03-30T18:00:00Z', subject: 'GSB — Thank You, Incredible Session', body: "Hi,\n\nWhat an extraordinary morning. The cohort was completely captivated — I had executives come up to me afterward saying it was the most valuable session they've attended in years.\n\nPlease send over the invoice when you're ready. And let's absolutely do this again next year.\n\nElena", from_name: 'Elena Vasquez', to_name: "Mori's Team", contact_id: 'c15a', channel: 'email', needs_response: true },
    ],
    alerts: [{ type: 'event_approaching', label: 'Event complete — invoice not yet sent', severity: 'high' }],
  },

  // invoice overdue — client says it's processing
  {
    id: 'e7',
    created_at: '2026-01-11T10:00:00Z',
    updated_at: '2026-03-29T16:00:00Z',
    last_activity_at: '2026-03-29T16:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'client_deliverables_sent', 'advance_sheet_complete'],
    post_event_flags: ['invoice_sent', 'media_uploaded'],
    organization: 'TechCorp',
    event_time: '1pm – 2pm PT',
    source: 'LinkedIn referral',
    contacts: [{
      id: 'c7a', first_name: 'Stephanie', last_name: 'Cho',
      email: 'scho@techcorp.io', title: 'Head of Learning & Development',
      role: 'primary', is_current_point_of_contact: true, status: 'client',
    }],
    event_name: 'TechCorp All-Hands Leadership Day',
    event_date: '2026-03-06',
    event_location: 'TechCorp HQ', event_city: 'San Francisco, CA',
    event_format: 'hybrid', audience_size: 600,
    topic: 'Negotiation Skills for Tech Leaders',
    session_length: 60, fee: 20000,
    travel_covered: true, hotel_covered: true,
    notes: 'Event March 5 — strong feedback. Invoice sent Mar 1, was due Mar 22. Now 32 days overdue. Stephanie says payment releasing Apr 6.',
    comms: [
      { id: 'cm7a', type: 'email_outbound', date: '2026-03-01T09:00:00Z', subject: 'Invoice #2026-004 — TechCorp Leadership Day', body: "Hi Stephanie,\n\nThank you for a wonderful event yesterday. Please find attached Invoice #2026-004 for $20,000, due March 27.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Stephanie Cho', contact_id: 'c7a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm7b', type: 'email_inbound', date: '2026-03-09T11:00:00Z', subject: 'Re: Invoice — Thank you!', body: "Hi Sarah,\n\nReceived! The session was absolutely phenomenal. Finance will process this on the 27th.\n\nSteph", from_name: 'Stephanie Cho', to_name: "Mori's Team", contact_id: 'c7a', channel: 'email', needs_response: false },
      { id: 'cm7c', type: 'email_inbound', date: '2026-03-29T16:00:00Z', subject: 'Re: Invoice #2026-004 — Payment Update', body: "Hi,\n\nSorry for the slight delay — finance had a system migration last week that held up a batch of payments. It's been released and should hit your account by Apr 6.\n\nSteph", from_name: 'Stephanie Cho', to_name: "Mori's Team", contact_id: 'c7a', channel: 'email', needs_response: false },
    ],
    alerts: [invoiceOverdue()],
  },

  // invoice paid, media received, pending final close-out
  {
    id: 'e16',
    created_at: '2026-01-06T10:00:00Z',
    updated_at: '2026-03-16T14:00:00Z',
    last_activity_at: '2026-03-16T14:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'client_deliverables_sent', 'advance_sheet_complete'],
    post_event_flags: ['invoice_sent', 'invoice_paid', 'media_uploaded', 'marked_complete'],
    organization: 'BlackRock',
    event_time: '10am – 11am',
    source: 'Referral from JPMorgan Chase',
    contacts: [{
      id: 'c16a', first_name: 'Sandra', last_name: 'Obi',
      email: 'sobi@blackrock.com', title: 'Head of Talent Development',
      role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
    }],
    event_name: "BlackRock Women's Leadership Forum",
    event_date: '2026-03-13',
    event_location: '50 Hudson Yards', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 220,
    topic: "Negotiation & Influence: A Framework for Senior Women",
    session_length: 60, fee: 25000,
    travel_covered: false, hotel_covered: false,
    notes: 'Excellent event March 12. Invoice paid March 15. Media received and uploaded. Needs marked complete.',
    comms: [
      { id: 'cm16a', type: 'email_outbound', date: '2026-03-14T09:00:00Z', subject: "Invoice #2026-003 — BlackRock Women's Leadership Forum", body: "Hi Sandra,\n\nThank you for a wonderful event yesterday. Please find attached Invoice #2026-003 for $25,000, due April 1.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Sandra Obi', contact_id: 'c16a', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm16b', type: 'email_inbound', date: '2026-03-16T14:00:00Z', subject: 'Re: Invoice + Media Files', body: "Hi Sarah,\n\nPayment sent this morning. Also attaching the professional photos and video recording from the session as promised.\n\nThe feedback has been extraordinary — we'll definitely be back in touch for next year.\n\nSandra", from_name: 'Sandra Obi', to_name: "Mori's Team", contact_id: 'c16a', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },

  // fully complete — gold standard reference
  {
    id: 'e8',
    created_at: '2025-11-02T10:00:00Z',
    updated_at: '2026-02-21T10:00:00Z',
    last_activity_at: '2026-02-21T10:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'client_deliverables_sent', 'advance_sheet_complete'],
    post_event_flags: ['invoice_sent', 'invoice_paid', 'media_uploaded', 'marked_complete'],
    organization: 'Goldman Sachs',
    event_time: '9am – 10:30am',
    source: 'Repeat client',
    contacts: [{
      id: 'c8a', first_name: 'James', last_name: 'Okafor',
      email: 'jokafor@goldmansachs.com', title: 'Chief Learning Officer',
      role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
      notes: 'Third engagement with Goldman. James is a champion — always fast to pay, always sends media.',
    }],
    event_name: 'GS Leadership Accelerator — Winter Cohort',
    event_date: '2026-02-13', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 85, fee: 30000,
    session_length: 90,
    topic: 'Power, Persuasion, and the Negotiation Table',
    notes: 'Third time working with James and Goldman. Flawless — paid same week, sent HD video and professional photos. Already discussing fall cohort.',
    comms: [
      { id: 'cm8a', type: 'email_inbound', date: '2026-02-15T10:00:00Z', subject: 'Re: Invoice — Wire Sent + Media', body: "Sarah,\n\nWire sent this morning for the full amount. Attaching the session recording and photos.\n\nThe cohort absolutely loved it. I've already spoken with my partner about bringing Mori back in October. Let's connect in April to discuss.\n\nJames", from_name: 'James Okafor', to_name: "Mori's Team", contact_id: 'c8a', channel: 'email', needs_response: false },
      { id: 'cm8b', type: 'stage_change', date: '2026-02-21T10:00:00Z', subject: 'Marked complete — payment confirmed, media uploaded', staff_name: 'Sarah K.', needs_response: false },
    ],
    alerts: [],
  },

  // ── MEDIA APPEARANCES ─────────────────────────────────────────────────────

  // podcast — pre-call is today April 1
  {
    id: 'em1',
    created_at: '2026-03-28T10:00:00Z',
    updated_at: '2026-03-30T13:00:00Z',
    last_activity_at: '2026-03-30T13:00:00Z',
    section: 'prospects',
    event_type: 'podcast',
    prospect_step: 'in_contact',
    engagement_flags: [], media_flags: [], post_event_flags: [],
    organization: 'How I Built This — Guy Raz / NPR',
    source: 'Direct outreach from producer',
    contacts: [{ id: 'cm1a_c', first_name: 'Jessica', last_name: 'Park', email: 'jpark@npr.org', title: 'Senior Producer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Negotiation, Authenticity & the Making of Bring Yourself',
    event_format: 'virtual',
    notes: 'Pre-call with Jessica scheduled for today at 2pm ET to align on topic angle. They want more personal backstory; we want to keep it leadership-focused.',
    comms: [
      { id: 'cm_em1a', type: 'email_inbound', date: '2026-03-28T10:00:00Z', subject: 'How I Built This — Guest Invitation for Mori Taheripour', body: "Hi,\n\nI'm a senior producer at How I Built This with Guy Raz. We've been following Mori's work and would love to have her on for a conversation about her journey — from professor to author to in-demand speaker.\n\nJessica Park\nSenior Producer, How I Built This / NPR", from_name: 'Jessica Park', to_name: "Mori's Team", contact_id: 'cm1a_c', channel: 'email', needs_response: false },
      { id: 'cm_em1b', type: 'email_outbound', date: '2026-03-29T09:00:00Z', subject: 'Re: How I Built This — Thank You, Topic Discussion', body: "Hi Jessica,\n\nThank you for reaching out — Mori would be delighted to join. We'd love to focus the conversation around her leadership philosophy and the themes in Bring Yourself.\n\nCould we schedule a brief pre-call to align on the angle?\n\nBest,\nRyan G.", from_name: "Mori's Team", to_name: 'Jessica Park', contact_id: 'cm1a_c', staff_name: 'Ryan G.', channel: 'email', needs_response: false },
      { id: 'cm_em1c', type: 'email_inbound', date: '2026-03-30T13:00:00Z', subject: 'Re: How I Built This — Pre-Call Today at 2pm ET', body: "Hi — just confirming our pre-call today at 2pm ET. Looking forward to it. We're also open to the leadership angle — just want some of the personal journey woven in.\n\nJessica", from_name: 'Jessica Park', to_name: "Mori's Team", contact_id: 'cm1a_c', channel: 'email', needs_response: false },
    ],
    calls: [
      { id: 'call_em1_1', type: 'discovery', status: 'scheduled', number: 1, scheduled_at: '2026-03-30', added_by: 'ai' },
    ],
    alerts: [],
  },

  // panel — confirmed, May 7, tech check still needed
  {
    id: 'em2',
    created_at: '2026-02-21T09:00:00Z',
    updated_at: '2026-03-23T11:00:00Z',
    last_activity_at: '2026-03-23T11:00:00Z',
    section: 'engagements',
    event_type: 'panel',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent', 'prep_sent'],
    post_event_flags: [],
    organization: 'World Economic Forum — Davos Connections Series',
    event_time: '2pm ET – 3pm ET',
    source: 'WEF invitation',
    contacts: [{ id: 'cm2a_c', first_name: 'Lena', last_name: 'Brandt', email: 'lbrandt@weforum.org', title: 'Program Director, Leadership', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'WEF Davos Connections — Women Redefining Negotiation',
    event_date: '2026-05-06',
    event_format: 'virtual',
    audience_size: 3500,
    topic: 'Women Redefining Negotiation in the 21st Century',
    fee: 8000,
    notes: 'Virtual panel — 4 panelists, 60 minutes, moderated. Bio and prep questions sent. Tech check not yet scheduled.',
    comms: [
      { id: 'cm_em2a', type: 'email_inbound', date: '2026-02-21T09:00:00Z', subject: 'WEF Davos Connections Series — Panel Invitation', body: "Dear Mori,\n\nThe World Economic Forum would like to invite you to participate as a panelist in our Davos Connections virtual series on May 7.\n\nLena Brandt\nProgram Director, WEF", from_name: 'Lena Brandt', to_name: "Mori's Team", contact_id: 'cm2a_c', channel: 'email', needs_response: false },
      { id: 'cm_em2b', type: 'email_outbound', date: '2026-03-02T10:00:00Z', subject: 'Re: WEF Panel — Confirmed + Bio & Headshot', body: "Hi Lena,\n\nMori would be delighted to participate. Attached is her official bio and high-resolution headshot.\n\nBest,\nSarah K.", from_name: "Mori's Team", to_name: 'Lena Brandt', contact_id: 'cm2a_c', staff_name: 'Sarah K.', channel: 'email', needs_response: false },
      { id: 'cm_em2c', type: 'email_inbound', date: '2026-03-23T11:00:00Z', subject: 'WEF Panel — Prep Questions + Zoom Details', body: "Hi Sarah,\n\nAll confirmed — bio received. Attached are the moderator's prep questions. Zoom link and tech check details to follow next week.\n\nLena", from_name: 'Lena Brandt', to_name: "Mori's Team", contact_id: 'cm2a_c', channel: 'email', needs_response: false },
    ],
    alerts: [{ type: 'event_approaching', label: 'Panel May 7 — tech check not yet scheduled', severity: 'medium' }],
  },

  // interview — published, complete
  {
    id: 'em3',
    created_at: '2026-02-02T10:00:00Z',
    updated_at: '2026-03-19T14:00:00Z',
    last_activity_at: '2026-03-19T14:00:00Z',
    section: 'post-event',
    event_type: 'interview',
    engagement_flags: [], media_flags: ['confirmed', 'bio_sent', 'prep_sent', 'day_of_ready'],
    post_event_flags: ['media_uploaded', 'marked_complete'],
    organization: 'Forbes',
    source: 'Editorial outreach',
    contacts: [{ id: 'cm3a_c', first_name: 'Rachel', last_name: 'Monroe', email: 'rmonroe@forbes.com', title: 'Senior Editor, Leadership', role: 'primary', is_current_point_of_contact: true, status: 'client' }],
    event_name: 'Forbes — "The Negotiators" Feature Series',
    event_date: '2026-03-11',
    event_format: 'virtual',
    topic: 'Why the Best Negotiators Never Bluff',
    notes: 'Published March 18. 42k reads in first week. Rachel already asking about a follow-up piece.',
    comms: [
      { id: 'cm_em3a', type: 'email_inbound', date: '2026-02-02T10:00:00Z', subject: 'Forbes Leadership — Interview Request', body: "Hi,\n\nI'm a senior editor at Forbes working on a feature series called 'The Negotiators.' Mori is at the top of our list.\n\nRachel Monroe\nForbes", from_name: 'Rachel Monroe', to_name: "Mori's Team", contact_id: 'cm3a_c', channel: 'email', needs_response: false },
      { id: 'cm_em3b', type: 'email_inbound', date: '2026-03-19T14:00:00Z', subject: 'Forbes Feature — Published Today!', body: "Hi,\n\nThe piece is live! It's already getting strong traction. Would Mori be open to a follow-up piece later this year?\n\nRachel", from_name: 'Rachel Monroe', to_name: "Mori's Team", contact_id: 'cm3a_c', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },
]

// ─── Review Queue ─────────────────────────────────────────────────────────────

export const MOCK_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: 'r1',
    received_at: '2026-03-30T07:55:00Z',
    from_name: 'Keisha Drummond',
    from_email: 'kdrummond@blackrock.com',
    subject: "Speaker Inquiry — BlackRock Women's Leadership Forum (Oct)",
    body_preview: "Hi, I'm Keisha Drummond, Head of Talent Development at BlackRock. We had an exceptional experience with Mori at our March forum and would love to have her back for our October session. Could we discuss availability?",
    account: 'team@moritaheripour.com',
    ai_confidence: 0.97,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Repeat client inquiry — past engagement on file. High confidence new opportunity. October timeframe gives good runway.',
  },
  {
    id: 'r2',
    received_at: '2026-03-30T09:15:00Z',
    from_name: 'Tom Ridley',
    from_email: 'tridley@hbr.org',
    subject: 'Harvard Business Review — Feature Collaboration',
    body_preview: "Following up on our earlier note — we'd love to explore a feature piece or podcast appearance with Mori around her negotiation framework and the themes from Bring Yourself. Would she be open to a brief call?",
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.62,
    state: 'needs_review',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Media/PR opportunity — potentially high value for brand. Lower confidence due to ambiguous scope and no fee attached.',
  },
  {
    id: 'r3',
    received_at: '2026-03-30T16:45:00Z',
    from_name: 'Mailchimp',
    from_email: 'noreply@mailchimp.com',
    subject: 'Your March campaign report is ready',
    body_preview: 'Your March newsletter reached 4,823 subscribers with a 34% open rate and 6.1% click rate — your highest engagement month this year...',
    account: 'team@moritaheripour.com',
    ai_confidence: 0.99,
    state: 'ai_sorted',
    ai_suggested_action: 'ignore',
    ai_reasoning: 'Automated Mailchimp report. No action required.',
  },
  {
    id: 'r4',
    received_at: '2026-03-30T11:20:00Z',
    from_name: 'Priya Mehta',
    from_email: 'pmehta@mckinsey.com',
    subject: 'McKinsey Global Leadership Summit — Availability Check',
    body_preview: "Hello, our events team is building the speaker roster for the McKinsey Global Leadership Summit in September 2026. Mori is at the top of our list for a keynote on negotiation. Could you confirm availability and share current rates?",
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.93,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Clear availability and rate inquiry from named McKinsey contact with specific event timeline. High-value opportunity.',
  },
  {
    id: 'r5',
    received_at: '2026-03-30T08:10:00Z',
    from_name: 'David Koslowski',
    from_email: 'dkoslowski@vistage.com',
    subject: 'Re: Vistage Summit — One More Ask',
    body_preview: "Hi, I wanted to follow up one more time on the fee discussion. Our board reviewed and unfortunately can't go above $22k. I know this isn't what you're looking for — is there truly no flexibility? We're huge fans of Mori's work.",
    account: 'team@moritaheripour.com',
    ai_confidence: 0.55,
    state: 'needs_review',
    ai_suggested_action: 'update_prospect',
    ai_reasoning: 'Follow-up on existing fee negotiation with Vistage (prospect e3). Client pushing back again on price — decision needed on whether to hold firm or offer alternative. Human judgment required.',
  },
  {
    id: 'r6',
    received_at: '2026-03-30T15:30:00Z',
    from_name: 'Google Alerts',
    from_email: 'googlealerts-noreply@google.com',
    subject: 'Google Alert — "Mori Taheripour"',
    body_preview: 'New mentions: (1) Forbes.com: "10 Negotiation Experts to Watch in 2026" — Mori ranked #4. (2) LinkedIn: Post shared 847 times from her recent article on authentic leadership...',
    account: 'team@moritaheripour.com',
    ai_confidence: 0.96,
    state: 'ai_sorted',
    ai_suggested_action: 'ignore',
    ai_reasoning: 'Automated Google Alert. Positive press mentions — no action required.',
  },
]

// ─── Mock Companies ───────────────────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'co1', name: 'Microsoft', industry: 'Technology', website: 'microsoft.com',
    watching: false,
    teams: [{ id: 't1', name: 'Global Learning & Development' }],
    engagement_ids: ['e2'], contact_ids: ['c2a', 'c2b'],
    notes: 'Via Keppler Speakers. Budget approval pending. Lauren is enthusiastic.',
  },
  {
    id: 'co2', name: 'Deloitte US', industry: 'Professional Services', website: 'deloitte.com',
    watching: true,
    teams: [{ id: 't2', name: 'Leadership Forum' }, { id: 't3', name: 'People & Culture' }],
    engagement_ids: ['e4'], contact_ids: ['c4a', 'c4b', 'c4c'],
    notes: 'Contract addendum arrived this morning — needs sign-off today.',
  },
  {
    id: 'co3', name: 'Wharton Executive Education', industry: 'Education', website: 'wharton.upenn.edu',
    watching: true,
    teams: [{ id: 't4', name: 'Executive Education' }, { id: 't5', name: "Women's Leadership" }],
    engagement_ids: ['e17'], contact_ids: ['c17a', 'c17b'],
    notes: "Today's event — Women in Leadership Summit, 10am Philadelphia. Fully confirmed.",
  },
  {
    id: 'co4', name: 'JPMorgan Chase', industry: 'Financial Services', website: 'jpmorgan.com',
    watching: false,
    teams: [{ id: 't6', name: "Women's Network" }],
    engagement_ids: ['e6'], contact_ids: ['c6a', 'c6b'],
    notes: 'Event Mar 316 — 14 days out. Briefing document needed urgently.',
  },
  {
    id: 'co5', name: 'Vistage Worldwide', industry: 'Executive Coaching', website: 'vistage.com',
    watching: true,
    teams: [],
    engagement_ids: ['e3'], contact_ids: ['c3a', 'c3b'],
    notes: 'Fee negotiation ongoing. Holding at $25k. David pushed back again today.',
  },
  {
    id: 'co6', name: 'Accenture', industry: 'Professional Services', website: 'accenture.com',
    watching: false,
    teams: [{ id: 't7', name: 'Inclusion & Diversity' }],
    engagement_ids: ['e1'], contact_ids: ['c1a'],
    notes: 'Fresh inbound this morning. Needs response.',
  },
  {
    id: 'co7', name: 'TechCorp', industry: 'Technology', website: 'techcorp.io',
    watching: false,
    teams: [],
    engagement_ids: ['e7'], contact_ids: ['c7a'],
    notes: 'Invoice 7 days overdue — Stephanie says payment releasing Apr 6.',
  },
  {
    id: 'co8', name: 'Goldman Sachs', industry: 'Financial Services', website: 'goldmansachs.com',
    watching: true,
    teams: [{ id: 't8', name: 'Leadership Accelerator' }],
    engagement_ids: ['e8'], contact_ids: ['c8a'],
    notes: 'Third engagement — always flawless. James hinting at October repeat.',
  },
  { id: 'co9',  name: 'Nike',        industry: 'Sports & Retail',      website: 'nike.com',          watching: false, teams: [],                                                  engagement_ids: ['e9'],       contact_ids: ['c9a'],          notes: 'Inquiry came in Wednesday. Portland offsite Jun 10.' },
  { id: 'co10', name: 'Salesforce',  industry: 'Technology',            website: 'salesforce.com',    watching: false, teams: [{ id: 't9', name: 'Sales Leadership' }],            engagement_ids: ['e10'],      contact_ids: ['c10a'],         notes: 'First outreach Mar 29. No response in 6 days.' },
  { id: 'co11', name: 'Mayo Clinic', industry: 'Healthcare',            website: 'mayo.edu',          watching: true,  teams: [{ id: 't10', name: 'Leadership Program' }],         engagement_ids: ['e11'],      contact_ids: ['c11a'],         notes: 'Goldman referral. First touch sent last Friday. High potential.' },
  { id: 'co12', name: 'Amazon',      industry: 'Technology',            website: 'amazon.com',        watching: true,  teams: [{ id: 't11', name: 'Global L&D' }],                engagement_ids: ['e12'],      contact_ids: ['c12a', 'c12b'], notes: 'Large hybrid — 800 attendees. Speaker packet sent yesterday.' },
  { id: 'co13', name: 'PwC',         industry: 'Professional Services', website: 'pwc.com',           watching: false, teams: [{ id: 't12', name: 'Partners Summit' }],            engagement_ids: ['e13'],      contact_ids: ['c13a'],         notes: 'Diana confirmed 90-min format yesterday. Ready for contract.' },
  { id: 'co14', name: 'Citi',        industry: 'Financial Services',    website: 'citi.com',          watching: false, teams: [{ id: 't13', name: 'Women in Finance' }],           engagement_ids: ['e14'],      contact_ids: ['c14a', 'c14b'], notes: 'CFO sign-off confirmed yesterday. Formal confirmation expected today.' },
  { id: 'co15', name: 'Stanford GSB',industry: 'Education',             website: 'gsb.stanford.edu',  watching: true,  teams: [{ id: 't14', name: 'Executive Programs' }],         engagement_ids: ['e15'],      contact_ids: ['c15a', 'c15b'], notes: 'Event was yesterday Mar 31 — great session. Elena sent glowing note. Invoice needed.' },
  { id: 'co16', name: 'BlackRock',   industry: 'Financial Services',    website: 'blackrock.com',     watching: true,  teams: [{ id: 't15', name: "Women's Leadership" }],         engagement_ids: ['e16'],      contact_ids: ['c16a'],         notes: 'Mar 13 event — complete and paid. Keisha already reaching out about October.' },
  { id: 'co17', name: 'NPR / How I Built This', industry: 'Media',            website: 'npr.org',         watching: true,  teams: [],                                               engagement_ids: ['em1'], contact_ids: ['cm1a_c'],  notes: 'Pre-call today at 2pm ET. Topic angle in discussion.' },
  { id: 'co18', name: 'World Economic Forum',   industry: 'Nonprofit / Policy', website: 'weforum.org',     watching: true,  teams: [{ id: 't16', name: 'Leadership Series' }],       engagement_ids: ['em2'], contact_ids: ['cm2a_c'],  notes: 'Panel May 7 confirmed. Tech check not yet scheduled.' },
  { id: 'co19', name: 'Forbes',                 industry: 'Media',              website: 'forbes.com',      watching: true,  teams: [{ id: 't17', name: 'Leadership Editorial' }],    engagement_ids: ['em3'], contact_ids: ['cm3a_c'],  notes: 'Feature published Mar 19. Rachel asking about follow-up.' },
  { id: 'co20', name: 'LinkedIn',               industry: 'Technology / Media', website: 'linkedin.com',    watching: false, teams: [{ id: 't18', name: 'Creator Partnerships' }],    engagement_ids: ['em4'], contact_ids: ['cm4a_c'],  notes: 'LinkedIn Live Mar 316 — 2,400 RSVPs already.' },
  {
    id: 'co21', name: 'Morgan Stanley', industry: 'Financial Services', website: 'morganstanley.com',
    watching: true, teams: [{ id: 't19', name: "Women Forward" }],
    engagement_ids: ['e5'], contact_ids: ['c5a'],
    notes: 'Contract signed Mar 26. Briefing document not yet drafted — May 15 event.',
  },
]

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: TeamUser[] = [
  {
    id: 'u1', name: 'Mori Taheripour', email: 'mori@moritaheripour.com',
    role: 'admin', account: 'mori@moritaheripour.com', avatar_initials: 'MT',
  },
  {
    id: 'u2', name: 'Ryan G.', email: 'team@moritaheripour.com',
    role: 'admin', account: 'team@moritaheripour.com', avatar_initials: 'RG',
  },
  {
    id: 'u3', name: 'Sarah K.', email: 'booking@moritaheripour.com',
    role: 'regular', account: 'booking@moritaheripour.com', avatar_initials: 'SK',
  },
  {
    id: 'u4', name: 'James L.', email: 'assistant@moritaheripour.com',
    role: 'regular', account: 'assistant@moritaheripour.com', avatar_initials: 'JL',
  },
]