import { Engagement, EngagementAlert, ReviewItem, Company, TeamUser } from '@/types'

function noResponse(since: string): EngagementAlert {
  return { type: 'no_response', label: `No reply in 48h — since ${since}`, severity: 'high', since }
}
function followUp(since: string): EngagementAlert {
  return { type: 'follow_up_due', label: `Sent ${since} — time to follow up`, severity: 'medium', since }
}
function eventApproaching(label: string): EngagementAlert {
  return { type: 'event_approaching', label, severity: 'high' }
}
function invoiceOverdue(): EngagementAlert {
  return { type: 'invoice_overdue', label: 'Invoice unpaid — 32 days outstanding', severity: 'high' }
}

export const MOCK_ENGAGEMENTS: Engagement[] = [
  // ── PROSPECTS ──────────────────────────────────────────────────────────────
  {
    id: 'e1',
    created_at: '2024-06-09T14:00:00Z',
    updated_at: '2024-06-09T14:00:00Z',
    last_activity_at: '2024-06-09T14:00:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [],
    post_event_flags: [],
    organization: 'Accenture',
    source: 'Website inquiry',
    contacts: [{ id: 'c1a', first_name: 'Anika', last_name: 'Thomas', email: 'anika.thomas@accenture.com', title: 'VP Inclusion & Diversity', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Inclusive Negotiation Practices',
    event_format: 'virtual',
    audience_size: 250,
    notes: 'Inbound via website. Interested in Q4 virtual workshop.',
    comms: [{
      id: 'cm1a', type: 'email_inbound', date: '2024-06-09T14:20:00Z',
      subject: 'Speaking Inquiry — Inclusion & Negotiation Workshop',
      body: "Hello,\n\nI'm the VP of Inclusion & Diversity at Accenture and came across Dr. Taheripour's work through her Wharton profile.\n\nWe're planning a virtual workshop in Q4 focused on helping underrepresented talent negotiate more effectively. Would she be available for a 60-90 minute session?\n\nWarm regards,\nAnika Thomas",
      from_name: 'Anika Thomas', to_name: "Mori's Team", contact_id: 'c1a', channel: 'email', needs_response: true, response_due_by: '2024-06-11T14:00:00Z',
    }],
    alerts: [noResponse('Jun 9')],
  },
  {
    id: 'e2',
    created_at: '2024-06-05T10:00:00Z',
    updated_at: '2024-06-12T10:00:00Z',
    last_activity_at: '2024-06-12T10:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [],
    post_event_flags: [],
    organization: 'Microsoft',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [
      { id: 'c2a', first_name: 'Lauren', last_name: 'Prescott', email: 'lprescott@microsoft.com', title: 'Director, Global Learning', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c2b', first_name: 'James', last_name: 'Hollis', email: 'jhollis@kepplerspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Microsoft LEAP Leadership Summit',
    event_date: '2024-12-05',
    event_location: 'Microsoft Campus', event_city: 'Redmond, WA',
    event_format: 'in_person', audience_size: 300,
    topic: 'The Negotiation Mindset', session_length: 60, fee: 26000,
    travel_covered: true, hotel_covered: true,
    notes: 'Positive intro call Jun 5. Awaiting internal budget approval.',
    comms: [
      { id: 'cm2a', type: 'email_inbound', date: '2024-06-05T09:00:00Z', subject: 'Microsoft LEAP Summit — Speaker Inquiry', body: 'Initial outreach via Keppler. Interested in Dec 5 date.', from_name: 'James Hollis', to_name: "Mori's Team", contact_id: 'c2b', channel: 'email', needs_response: false },
      { id: 'cm2b', type: 'call', date: '2024-06-05T14:00:00Z', subject: 'Intro call — 30 min', body: 'Great call with Lauren. Very interested. Needs internal approval.', from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm2c', type: 'email_outbound', date: '2024-06-06T10:00:00Z', subject: "Re: Microsoft LEAP — Next Steps", body: "Sent follow-up with Mori's bio, topic overview, and fee range.", from_name: "Mori's Team", to_name: 'Lauren Prescott', contact_id: 'c2a', staff_name: 'EA', channel: 'email', needs_response: false },
    ],
    alerts: [followUp('Jun 6')],
  },
  {
    id: 'e3',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-10T09:00:00Z',
    last_activity_at: '2024-06-10T09:00:00Z',
    section: 'prospects',
    prospect_step: 'discussing',
    engagement_flags: [],
    post_event_flags: [],
    organization: 'Vistage Worldwide',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c3a', first_name: 'David', last_name: 'Koslowski', email: 'dkoslowski@vistage.com', title: 'Program Director', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true },
      { id: 'c3b', first_name: 'Nina', last_name: 'Okafor', email: 'nokafor@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    event_name: 'Vistage CEO Peer Group Summit',
    event_date: '2024-11-14',
    event_location: 'Marriott Marquis', event_city: 'Chicago, IL',
    event_format: 'in_person', audience_size: 120,
    topic: 'Navigating Difficult Conversations as a CEO',
    session_length: 90, fee: 25000,
    travel_covered: true, hotel_covered: true,
    notes: 'Back and forth on fee. David wants 90 min for $22k. Holding at $25k.',
    comms: [{
      id: 'cm3a', type: 'email_inbound', date: '2024-06-08T10:00:00Z',
      subject: 'Re: Vistage Summit — Fee Discussion',
      body: 'David came back asking if we could do $22k for the 90-min slot. Budget is tight.',
      from_name: 'David Koslowski', to_name: "Mori's Team", contact_id: 'c3a', channel: 'email', needs_response: true, response_due_by: '2024-06-11T00:00:00Z',
    }],
    alerts: [noResponse('Jun 8')],
  },
  // ── ADDITIONAL PROSPECTS ──────────────────────────────────────────────────
  {
    id: 'e9',
    created_at: '2024-06-11T09:00:00Z',
    updated_at: '2024-06-11T09:00:00Z',
    last_activity_at: '2024-06-11T09:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'BlackRock',
    source: 'Direct outreach',
    contacts: [{ id: 'c9a', first_name: 'Sandra', last_name: 'Obi', email: 'sobi@blackrock.com', title: 'Head of Talent Development', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: "Women's Leadership Forum",
    event_format: 'in_person', audience_size: 200, fee: 24000,
    event_date: '2024-10-15', event_city: 'New York, NY',
    notes: 'Mori reached out directly. No reply yet.',
    comms: [{ id: 'cm9a', type: 'email_outbound', date: '2024-06-11T09:00:00Z', subject: "Speaker Introduction — BlackRock Women's Leadership Forum", body: 'Sent intro email with bio and topic overview. Awaiting response.', from_name: "Mori's Team", to_name: 'Sandra Obi', contact_id: 'c9a', staff_name: 'EA', channel: 'email', needs_response: false }],
    alerts: [followUp('Jun 11')],
  },
  {
    id: 'e10',
    created_at: '2024-06-08T14:00:00Z',
    updated_at: '2024-06-10T10:00:00Z',
    last_activity_at: '2024-06-10T10:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'McKinsey & Company',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [{ id: 'c10a', first_name: 'Priya', last_name: 'Mehta', email: 'pmehta@mckinsey.com', title: 'Events Lead', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Leadership Summit Keynote',
    event_format: 'in_person', audience_size: 400, fee: 30000,
    event_date: '2025-03-10', event_city: 'Washington, DC',
    notes: 'Via WSB. Availability check sent.',
    comms: [{ id: 'cm10a', type: 'email_outbound', date: '2024-06-08T14:00:00Z', subject: "Availability Check — McKinsey Leadership Summit", body: "Sent availability confirmation and initial fee range.", from_name: "Mori's Team", to_name: 'Priya Mehta', contact_id: 'c10a', staff_name: 'Booker', channel: 'email', needs_response: false }],
    alerts: [followUp('Jun 8')],
  },
  {
    id: 'e11',
    created_at: '2024-06-10T11:00:00Z',
    updated_at: '2024-06-10T11:00:00Z',
    last_activity_at: '2024-06-10T11:00:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Salesforce',
    source: 'Website inquiry',
    contacts: [{ id: 'c11a', first_name: 'Tom', last_name: 'Nguyen', email: 'tnguyen@salesforce.com', title: 'Director, L&D', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: "Negotiation for Sales Leaders",
    event_format: 'virtual', audience_size: 500,
    notes: 'Inbound from website. High-volume virtual event.',
    comms: [{ id: 'cm11a', type: 'email_inbound', date: '2024-06-10T11:00:00Z', subject: "Speaker Inquiry — Salesforce Sales Summit", body: 'Hi, we are planning a virtual summit for our global sales leaders and would love to have Dr. Taheripour speak on negotiation. Could you share availability and rates?', from_name: 'Tom Nguyen', to_name: "Mori's Team", contact_id: 'c11a', channel: 'email', needs_response: true }],
    alerts: [noResponse('Jun 10')],
  },
  {
    id: 'e12',
    created_at: '2024-06-07T16:00:00Z',
    updated_at: '2024-06-09T09:00:00Z',
    last_activity_at: '2024-06-09T09:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'PwC',
    source: 'Keppler Speakers',
    booker_name: 'Keppler Speakers',
    contacts: [{ id: 'c12a', first_name: 'Anna', last_name: 'Chen', email: 'achen@pwc.com', title: 'Chief People Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: "Leading Through Uncertainty",
    event_format: 'in_person', audience_size: 150, fee: 22000,
    event_date: '2024-11-20', event_city: 'Chicago, IL',
    notes: 'Good initial call. Sending topic brief next.',
    comms: [
      { id: 'cm12a', type: 'email_inbound', date: '2024-06-07T16:00:00Z', subject: "PwC Leadership Retreat — Speaker Inquiry", body: "Inbound via Keppler. Interested in November retreat.", from_name: 'James at Keppler', to_name: "Mori's Team", contact_id: 'c12a', channel: 'email', needs_response: false },
      { id: 'cm12b', type: 'call', date: '2024-06-09T09:00:00Z', subject: "Intro call — 20 min", body: "Good call with Anna. Very aligned on topic. Sending brief.", from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
    ],
    alerts: [],
  },

  {
    id: 'e9',
    created_at: '2024-06-11T09:00:00Z',
    updated_at: '2024-06-11T09:00:00Z',
    last_activity_at: '2024-06-11T09:00:00Z',
    section: 'prospects',
    prospect_step: 'inquiry',
    engagement_flags: [], post_event_flags: [],
    organization: 'Nike',
    source: 'Direct inquiry',
    contacts: [{ id: 'c9a', first_name: 'Tanya', last_name: 'Rhodes', email: 'trhodes@nike.com', title: 'Director of Leadership Development', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'Negotiation & Influence in Sports Business',
    event_format: 'in_person', audience_size: 200,
    notes: 'Inbound via website. Looking for keynote for leadership offsite.',
    comms: [{ id: 'cm9a', type: 'email_inbound', date: '2024-06-11T09:00:00Z', subject: 'Speaking Inquiry — Nike Leadership Offsite', body: "Hi, we're planning a leadership offsite in Q3 and Dr. Taheripour's work on negotiation would be a perfect fit. Would she be available?", from_name: 'Tanya Rhodes', to_name: "Mori's Team", contact_id: 'c9a', channel: 'email', needs_response: true }],
    alerts: [{ type: 'no_response', label: 'No reply in 48h — since Jun 11', severity: 'high', since: 'Jun 11' }],
  },
  {
    id: 'e10',
    created_at: '2024-06-10T11:00:00Z',
    updated_at: '2024-06-10T11:00:00Z',
    last_activity_at: '2024-06-10T11:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Salesforce',
    source: 'Outreach by team',
    contacts: [{ id: 'c10a', first_name: 'Marcus', last_name: 'Lin', email: 'mlin@salesforce.com', title: 'VP People & Culture', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' }],
    topic: 'The Art of Negotiation for Sales Leaders',
    event_format: 'virtual', audience_size: 500,
    event_date: '2024-10-15', event_city: 'Virtual',
    notes: 'Team reached out. No response yet.',
    comms: [{ id: 'cm10a', type: 'email_outbound', date: '2024-06-10T11:00:00Z', subject: 'Speaking Opportunity — Salesforce Leadership Summit', body: "Hi Marcus, we're reaching out on behalf of Dr. Mori Taheripour regarding your upcoming leadership summit. We'd love to explore a keynote on negotiation.", from_name: "Mori's Team", to_name: 'Marcus Lin', contact_id: 'c10a', staff_name: 'EA', channel: 'email', needs_response: false }],
    alerts: [{ type: 'follow_up_due', label: 'Sent Jun 10 — time to follow up', severity: 'medium', since: 'Jun 10' }],
  },
  {
    id: 'e11',
    created_at: '2024-06-08T14:00:00Z',
    updated_at: '2024-06-11T10:00:00Z',
    last_activity_at: '2024-06-11T10:00:00Z',
    section: 'prospects',
    prospect_step: 'outreach',
    engagement_flags: [], post_event_flags: [],
    organization: 'Mayo Clinic',
    source: 'Referral from Goldman Sachs',
    contacts: [{ id: 'c11a', first_name: 'Sarah', last_name: 'Okonkwo', email: 'sokonkwo@mayo.edu', title: 'Chief Human Resources Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active', watching: true }],
    topic: 'Negotiation Skills for Healthcare Leaders',
    event_format: 'in_person', audience_size: 150,
    event_city: 'Rochester, MN',
    notes: 'Referral from James Okafor at Goldman. High potential.',
    comms: [{ id: 'cm11a', type: 'email_outbound', date: '2024-06-08T14:00:00Z', subject: 'Introduction — Dr. Mori Taheripour', body: "Hi Sarah, James Okafor at Goldman Sachs suggested we reach out. Dr. Taheripour would love to connect about your upcoming leadership program.", from_name: "Mori's Team", to_name: 'Sarah Okonkwo', contact_id: 'c11a', staff_name: 'EA', channel: 'email', needs_response: false }],
    alerts: [{ type: 'follow_up_due', label: 'Sent Jun 8 — time to follow up', severity: 'medium', since: 'Jun 8' }],
  },
  {
    id: 'e12',
    created_at: '2024-06-03T09:00:00Z',
    updated_at: '2024-06-10T16:00:00Z',
    last_activity_at: '2024-06-10T16:00:00Z',
    section: 'prospects',
    prospect_step: 'in_contact',
    engagement_flags: [], post_event_flags: [],
    organization: 'Amazon',
    source: 'Washington Speakers Bureau',
    booker_name: 'Washington Speakers Bureau',
    contacts: [
      { id: 'c12a', first_name: 'Patricia', last_name: 'Yuen', email: 'pyuen@amazon.com', title: 'Global Head of L&D', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
      { id: 'c12b', first_name: 'Carlos', last_name: 'Mendes', email: 'cmendes@washingtonspeakers.com', title: 'Agent', role: 'bureau', is_current_point_of_contact: false },
    ],
    topic: 'Inclusive Leadership & Negotiation',
    event_format: 'hybrid', audience_size: 800,
    event_date: '2024-11-20', event_city: 'Seattle, WA',
    fee: 32000, travel_covered: true, hotel_covered: true,
    notes: 'Initial call went well. Patricia is the decision maker. Scheduling follow-up.',
    comms: [
      { id: 'cm12a', type: 'email_inbound', date: '2024-06-03T09:00:00Z', subject: 'Amazon Leadership Conference — Speaker Inquiry', body: 'Via Washington Speakers Bureau. Interested in Nov 20 date for global leadership conference.', from_name: 'Carlos Mendes', to_name: "Mori's Team", contact_id: 'c12b', channel: 'email', needs_response: false },
      { id: 'cm12b', type: 'call', date: '2024-06-07T15:00:00Z', subject: 'Intro call — 45 min', body: 'Great call with Patricia. Very engaged. Scheduling follow-up with her team.', from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm12c', type: 'email_outbound', date: '2024-06-10T16:00:00Z', subject: 'Re: Amazon Leadership Conference — Next Steps', body: "Sent Mori's speaker packet and proposed dates for a follow-up call.", from_name: "Mori's Team", to_name: 'Patricia Yuen', contact_id: 'c12a', staff_name: 'EA', channel: 'email', needs_response: false },
    ],
    alerts: [],
  },
  {
    id: 'e13',
    created_at: '2024-05-28T10:00:00Z',
    updated_at: '2024-06-09T14:00:00Z',
    last_activity_at: '2024-06-09T14:00:00Z',
    section: 'prospects',
    prospect_step: 'discussing',
    engagement_flags: [], post_event_flags: [],
    organization: 'PwC',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c13a', first_name: 'Diana', last_name: 'Nakamura', email: 'diana.nakamura@pwc.com', title: 'Chief Talent Officer', role: 'primary', is_current_point_of_contact: true, status: 'prospect_active' },
    ],
    topic: 'Negotiation Strategy for Professional Services',
    event_format: 'in_person', audience_size: 300,
    event_date: '2024-09-25', event_city: 'New York, NY',
    fee: 24000, travel_covered: true, hotel_covered: false,
    notes: 'Deep in discussions. Diana loves the topic. Working through date and format.',
    comms: [
      { id: 'cm13a', type: 'email_inbound', date: '2024-05-28T10:00:00Z', subject: 'PwC Partners Summit — Speaker Inquiry', body: 'Inquiry via Premier. Interested in Sep 25 date for partners summit.', from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: false },
      { id: 'cm13b', type: 'call', date: '2024-06-04T11:00:00Z', subject: 'Discovery call — 30 min', body: 'Great chemistry. Diana very interested. Discussing format — 60 vs 90 min.', from_name: 'EA', staff_name: 'EA', channel: 'phone', needs_response: false },
      { id: 'cm13c', type: 'email_inbound', date: '2024-06-09T14:00:00Z', subject: 'Re: PwC Partners Summit — Format Discussion', body: "Hi, we'd prefer the 90-minute deep-dive format. Can you confirm availability and send a draft agreement?", from_name: 'Diana Nakamura', to_name: "Mori's Team", contact_id: 'c13a', channel: 'email', needs_response: true },
    ],
    alerts: [{ type: 'no_response', label: 'No reply in 48h — since Jun 9', severity: 'high', since: 'Jun 9' }],
  },
  // ── ENGAGEMENTS ────────────────────────────────────────────────────────────
  {
    id: 'e4',
    created_at: '2024-05-15T09:00:00Z',
    updated_at: '2024-06-11T09:15:00Z',
    last_activity_at: '2024-06-11T09:15:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent'],
    post_event_flags: [],
    organization: 'Deloitte US',
    source: 'Premier Speakers Bureau',
    booker_name: 'Premier Speakers Bureau',
    contacts: [
      { id: 'c4a', first_name: 'Marcus', last_name: 'Webb', email: 'marcus.webb@deloitte.com', phone: '212-555-0202', title: 'Chief People Officer', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c4b', first_name: 'Jennifer', last_name: 'Park', email: 'jennifer.park@deloitte.com', title: 'EA to CPO', role: 'assistant', is_current_point_of_contact: false, notes: 'Handles all logistics for Marcus' },
      { id: 'c4c', first_name: 'David', last_name: 'Chen', email: 'dchen@deloitte-legal.com', title: 'Associate General Counsel', role: 'legal', is_current_point_of_contact: false, notes: 'Reviewing contract — minor IP/recording addenda' },
    ],
    event_name: 'Deloitte Leadership Forum 2024',
    event_date: '2024-10-03',
    event_location: 'Deloitte University', event_city: 'Westlake, TX',
    event_format: 'in_person', audience_size: 400,
    topic: 'The Art of Negotiation in High-Stakes Environments',
    session_length: 60, fee: 28000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Handheld mic, full AV team on site',
    notes: 'Contract sent Jun 8. Legal review in progress.',
    comms: [
      { id: 'cm4a', type: 'email_outbound', date: '2024-06-08T10:00:00Z', subject: 'Deloitte Leadership Forum — Speaking Agreement', body: "Sent contract to Marcus, cc'd Jennifer.", from_name: "Mori's Team", to_name: 'Marcus Webb', contact_id: 'c4a', staff_name: 'Booker', channel: 'email', needs_response: false },
      { id: 'cm4b', type: 'email_inbound', date: '2024-06-11T09:15:00Z', subject: 'Re: Deloitte Leadership Forum — Contract Review', body: "Hi,\n\nThank you for sending over the agreement. Our legal team has a few minor points — nothing major, just standard Deloitte addenda around IP and recording rights.\n\nCould we schedule a brief call this week?\n\nBest,\nMarcus", from_name: 'Marcus Webb', to_name: "Mori's Team", contact_id: 'c4a', channel: 'email', needs_response: true, response_due_by: '2024-06-13T00:00:00Z' },
    ],
    alerts: [noResponse('Jun 11')],
  },
  {
    id: 'e5',
    created_at: '2024-05-01T10:00:00Z',
    updated_at: '2024-06-10T14:00:00Z',
    last_activity_at: '2024-06-10T14:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed'],
    post_event_flags: [],
    organization: 'Wharton Executive Education',
    source: 'Repeat client',
    contacts: [{
      id: 'c5a', first_name: 'Rachel', last_name: 'Simmons',
      email: 'rsimmons@wharton.upenn.edu', phone: '215-555-0101',
      title: 'Director of Executive Education', role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
      notes: 'Returning client. Prefers email. Very organized.',
    }],
    event_name: 'Women in Leadership Summit',
    event_date: '2024-09-12',
    event_location: 'Huntsman Hall', event_city: 'Philadelphia, PA',
    event_format: 'in_person', audience_size: 250,
    topic: 'Negotiation & Influence for Executive Women',
    session_length: 75, fee: 22000,
    travel_covered: true, hotel_covered: true,
    av_needs: 'Lapel mic, clicker, HDMI, confidence monitor',
    notes: 'Contract signed. Advance sheet not yet generated — event Sep 12.',
    comms: [
      { id: 'cm5a', type: 'email_outbound', date: '2024-05-20T10:00:00Z', subject: 'Women in Leadership Summit — Contract', body: 'Sent contract. Rachel signed within 24 hours.', from_name: "Mori's Team", to_name: 'Rachel Simmons', contact_id: 'c5a', staff_name: 'EA', channel: 'email', needs_response: false },
      { id: 'cm5b', type: 'stage_change', date: '2024-05-21T11:00:00Z', subject: 'Contract signed — moved to Confirmed', staff_name: 'EA', needs_response: false },
    ],
    alerts: [eventApproaching('Event Sep 12 — advance sheet not yet sent')],
  },
  {
    id: 'e6',
    created_at: '2024-04-20T08:00:00Z',
    updated_at: '2024-06-10T11:00:00Z',
    last_activity_at: '2024-06-10T11:00:00Z',
    section: 'engagements',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed'],
    post_event_flags: [],
    organization: 'JPMorgan Chase',
    source: 'Direct outreach',
    contacts: [
      { id: 'c6a', first_name: 'Priya', last_name: 'Nair', email: 'priya.nair@jpmorgan.com', title: 'Managing Director, Talent', role: 'primary', is_current_point_of_contact: true, status: 'client' },
      { id: 'c6b', first_name: 'Tom', last_name: 'Everett', email: 'tom.everett@jpmorgan.com', title: 'AV & Events Coordinator', role: 'av', is_current_point_of_contact: false, notes: 'Room moved to main auditorium on 2' },
    ],
    event_name: "Chase Women's Network Annual Conference",
    event_date: '2024-07-18',
    event_location: '383 Madison Ave', event_city: 'New York, NY',
    event_format: 'in_person', audience_size: 180,
    topic: 'Negotiating Your Worth: Strategies for Senior Women',
    session_length: 45, fee: 18000,
    travel_covered: false, hotel_covered: false,
    av_needs: 'Podium mic, projector — no clicker needed',
    notes: 'Advance sheet complete. Room moved to main auditorium on 2.',
    comms: [{
      id: 'cm6a', type: 'email_inbound', date: '2024-06-10T11:00:00Z',
      subject: 'Advance Sheet Confirmation — July 18',
      body: "Hi,\n\nJust confirming receipt of the advance sheet — everything looks great! One small update: room moved to main auditorium on 2.\n\nLooking forward!\nPriya",
      from_name: 'Priya Nair', to_name: "Mori's Team", contact_id: 'c6a', channel: 'email', needs_response: false,
    }],
    alerts: [],
  },
  // ── POST-EVENT ─────────────────────────────────────────────────────────────
  {
    id: 'e7',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-07T16:00:00Z',
    last_activity_at: '2024-06-07T16:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: ['invoice_sent'],
    organization: 'TechCorp',
    source: 'LinkedIn referral',
    contacts: [{
      id: 'c7a', first_name: 'Stephanie', last_name: 'Cho',
      email: 'scho@techcorp.io', title: 'Head of Learning & Development',
      role: 'primary', is_current_point_of_contact: true, status: 'client',
    }],
    event_name: 'TechCorp All-Hands Leadership Day',
    event_date: '2024-05-22',
    event_location: 'TechCorp HQ', event_city: 'San Francisco, CA',
    event_format: 'hybrid', audience_size: 600,
    topic: 'Negotiation Skills for Tech Leaders',
    session_length: 60, fee: 20000,
    travel_covered: true, hotel_covered: true,
    notes: 'Event complete. Invoice sent May 30. Payment due June 30.',
    comms: [{
      id: 'cm7a', type: 'email_inbound', date: '2024-06-07T16:00:00Z',
      subject: 'Invoice #2024-006 — Payment Update',
      body: "Hi,\n\nJust a heads up — finance has the invoice and payment is processing. Should hit your account by June 28.\n\nThe session was phenomenal!\n\nSteph",
      from_name: 'Stephanie Cho', to_name: "Mori's Team", contact_id: 'c7a', channel: 'email', needs_response: false,
    }],
    alerts: [invoiceOverdue()],
  },
  {
    id: 'e8',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-04-15T10:00:00Z',
    last_activity_at: '2024-04-15T10:00:00Z',
    section: 'post-event',
    engagement_flags: ['contract_sent', 'contract_signed', 'advance_sheet_sent', 'logistics_confirmed', 'day_of_ready'],
    post_event_flags: ['invoice_sent', 'invoice_paid', 'media_uploaded', 'marked_complete'],
    organization: 'Goldman Sachs',
    source: 'Referral',
    contacts: [{
      id: 'c8a', first_name: 'James', last_name: 'Okafor',
      email: 'jokafor@goldmansachs.com', title: 'Chief Learning Officer',
      role: 'primary', is_current_point_of_contact: true, status: 'client', watching: true,
    }],
    event_name: 'GS Leadership Accelerator',
    event_date: '2024-04-10', event_city: 'New York, NY',
    event_format: 'in_person', fee: 30000,
    topic: 'Power, Persuasion, and the Negotiation Table',
    notes: 'Completed. Invoice paid April 15. Media received.',
    comms: [{
      id: 'cm8a', type: 'email_inbound', date: '2024-04-15T10:00:00Z',
      subject: 'Payment Confirmation',
      body: 'Wire transfer sent. Thank you for an excellent session.',
      from_name: 'James Okafor', to_name: "Mori's Team", contact_id: 'c8a', channel: 'email', needs_response: false,
    }],
    alerts: [],
  },
]

// ─── Review Queue Mock Data ───────────────────────────────────────────────────

export const MOCK_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: 'r1',
    received_at: '2024-06-12T08:30:00Z',
    from_name: 'Sandra Obi',
    from_email: 'sobi@blackrock.com',
    subject: "Speaker Inquiry — BlackRock Women's Leadership Forum",
    body_preview: "Hi, I'm the Head of Talent Development at BlackRock and we're looking for a keynote speaker for our annual Women's Leadership Forum in October. I came across Dr. Taheripour's work and believe she would be a perfect fit...",
    account: 'team@moritaheripour.com',
    ai_confidence: 0.94,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Clear speaking inquiry with event details, timeline, and decision-maker contact. High confidence this is a new business opportunity.',
  },
  {
    id: 'r2',
    received_at: '2024-06-12T09:15:00Z',
    from_name: 'Tom Ridley',
    from_email: 'tridley@hbr.org',
    subject: 'Re: Harvard Business Review — Potential Collaboration',
    body_preview: "Following up on our earlier conversation — we'd love to explore a feature piece or podcast appearance with Dr. Taheripour around her negotiation framework. Would she be open to a brief call?",
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.61,
    state: 'needs_review',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Media/collaboration inquiry — not a traditional speaking engagement but potentially high value. Confidence lower due to ambiguity of scope.',
  },
  {
    id: 'r3',
    received_at: '2024-06-11T16:45:00Z',
    from_name: 'Mailchimp',
    from_email: 'noreply@mailchimp.com',
    subject: 'Your monthly campaign report is ready',
    body_preview: 'Your June newsletter campaign reached 4,823 subscribers with a 34% open rate...',
    account: 'team@moritaheripour.com',
    ai_confidence: 0.98,
    state: 'ai_sorted',
    ai_suggested_action: 'ignore',
    ai_reasoning: 'Automated marketing platform notification. No business action required.',
  },
  {
    id: 'r4',
    received_at: '2024-06-11T11:20:00Z',
    from_name: 'Priya Mehta',
    from_email: 'pmehta@mckinsey.com',
    subject: 'McKinsey Leadership Summit — Availability Check',
    body_preview: 'Hello, our events team is putting together the speaker roster for the McKinsey Leadership Summit in March 2025. We have Dr. Taheripour on our shortlist for a keynote on negotiation and influence...',
    account: 'booking@moritaheripour.com',
    ai_confidence: 0.91,
    state: 'ai_sorted',
    ai_suggested_action: 'create_prospect',
    ai_reasoning: 'Clear availability inquiry from a major organization with specific event details and a named decision-maker.',
  },
]

// ─── Mock Companies ───────────────────────────────────────────────────────────


export const MOCK_COMPANIES: Company[] = [
  {
    id: 'co1', name: 'Microsoft', industry: 'Technology', website: 'microsoft.com',
    watching: false,
    teams: [{ id: 't1', name: 'Global Learning & Development' }],
    engagement_ids: ['e2'], contact_ids: ['c2a', 'c2b'],
    notes: 'Via Keppler Speakers. Multiple departments interested.',
  },
  {
    id: 'co2', name: 'Deloitte US', industry: 'Professional Services', website: 'deloitte.com',
    watching: true,
    teams: [{ id: 't2', name: 'Leadership Forum' }, { id: 't3', name: 'People & Culture' }],
    engagement_ids: ['e4'], contact_ids: ['c4a', 'c4b', 'c4c'],
    notes: 'Strong relationship with CPO Marcus Webb. Legal team involved in contracts.',
  },
  {
    id: 'co3', name: 'Wharton Executive Education', industry: 'Education', website: 'wharton.upenn.edu',
    watching: true,
    teams: [{ id: 't4', name: 'Executive Education' }, { id: 't5', name: "Women's Leadership" }],
    engagement_ids: ['e5'], contact_ids: ['c5a'],
    notes: 'Repeat client. Rachel Simmons is primary. Strong relationship.',
  },
  {
    id: 'co4', name: 'JPMorgan Chase', industry: 'Financial Services', website: 'jpmorgan.com',
    watching: false,
    teams: [{ id: 't6', name: "Women's Network" }],
    engagement_ids: ['e6'], contact_ids: ['c6a', 'c6b'],
    notes: '',
  },
  {
    id: 'co5', name: 'Vistage Worldwide', industry: 'Executive Coaching', website: 'vistage.com',
    watching: true,
    teams: [],
    engagement_ids: ['e3'], contact_ids: ['c3a', 'c3b'],
    notes: 'Fee negotiation stalled. Worth revisiting.',
  },
  {
    id: 'co6', name: 'Accenture', industry: 'Professional Services', website: 'accenture.com',
    watching: false,
    teams: [{ id: 't7', name: 'Inclusion & Diversity' }],
    engagement_ids: ['e1'], contact_ids: ['c1a'],
    notes: 'Inbound inquiry. No response yet.',
  },
  {
    id: 'co7', name: 'TechCorp', industry: 'Technology', website: 'techcorp.io',
    watching: false,
    teams: [],
    engagement_ids: ['e7'], contact_ids: ['c7a'],
    notes: 'Invoice pending.',
  },
  { id: 'co9',  name: 'Nike',      industry: 'Sports & Retail',       website: 'nike.com',       watching: false, teams: [],                                                engagement_ids: ['e9'],  contact_ids: ['c9a'],         notes: 'Inbound inquiry. Leadership offsite Q3.' },
  { id: 'co10', name: 'Salesforce', industry: 'Technology',             website: 'salesforce.com', watching: false, teams: [{ id: 't9',  name: 'Sales Leadership' }],        engagement_ids: ['e10'], contact_ids: ['c10a'],        notes: 'Outreach by team. No response yet.' },
  { id: 'co11', name: 'Mayo Clinic',industry: 'Healthcare',             website: 'mayo.edu',       watching: true,  teams: [{ id: 't10', name: 'Leadership Program' }],       engagement_ids: ['e11'], contact_ids: ['c11a'],        notes: 'Goldman referral. High potential.' },
  { id: 'co12', name: 'Amazon',     industry: 'Technology',             website: 'amazon.com',     watching: true,  teams: [{ id: 't11', name: 'Global L&D' }],              engagement_ids: ['e12'], contact_ids: ['c12a', 'c12b'], notes: 'Via Washington Speakers Bureau. Large audience.' },
  { id: 'co13', name: 'PwC',        industry: 'Professional Services',  website: 'pwc.com',        watching: false, teams: [{ id: 't12', name: 'Partners Summit' }],          engagement_ids: ['e13'], contact_ids: ['c13a'],        notes: 'Deep in discussions. Strong fit.' },
  {
    id: 'co8', name: 'Goldman Sachs', industry: 'Financial Services', website: 'goldmansachs.com',
    watching: true,
    teams: [{ id: 't8', name: 'Leadership Accelerator' }],
    engagement_ids: ['e8'], contact_ids: ['c8a'],
    notes: 'Excellent engagement. High-value relationship to maintain.',
  },
]

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: TeamUser[] = [
  {
    id: 'u1', name: 'Mori Taheripour', email: 'mori@moritaheripour.com',
    role: 'admin', account: 'mori@moritaheripour.com', avatar_initials: 'MT',
  },
  {
    id: 'u2', name: 'Ryan G.', email: 'team@moritaheripour.com',
    role: 'admin', account: 'team@moritaheripour.com', avatar_initials: 'RG',
  },
  {
    id: 'u3', name: 'Sarah K.', email: 'booking@moritaheripour.com',
    role: 'regular', account: 'booking@moritaheripour.com', avatar_initials: 'SK',
  },
  {
    id: 'u4', name: 'James L.', email: 'assistant@moritaheripour.com',
    role: 'regular', account: 'assistant@moritaheripour.com', avatar_initials: 'JL',
  },
]